### ISSUE TITLE
assemblyQC 5 orgs for the FDA ARGOS BioProject

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#108]
All mock table work, and protocol updates for assemblyQC need to be completed before this task is possible. trying to figure out how to make this a subtask to those tasks. Bare with me 
- [ ] Ask @Jgergely11 to review table once complete @JingyueWu

**Comment by steph-sing** [comment]
@penningtonea FYI on this task before then end of the month. Let me know which 5 you select (update this ticket with that info).

**Comment by penningtonea** [comment]
SAMN16357584
SAMN16357271
SAMN13450482
SAMN16357234
SAMN16357182

**Comment by steph-sing** [comment]
please send corresponding genome assembly IDs

**Comment by penningtonea** [comment]
SAMN16357584 - GCA_019048125.1
SAMN16357271 - GCA_016766895.1
SAMN13450482 - GCA_016025875.1
SAMN16357234 - GCA_016127795.1
SAMN16357182 - GCA_016599775.1
