### ISSUE TITLE
Writeup request to get HIV reference genomic sequences from NIAID EQAPOL project

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#109]

**Comment by steph-sing** [comment]
-[] @JingyueWu follow up on whether the HIVE team submitted this write-up to Duke, and when/if we will receive this data.
-[] @millicentq Please provide a status update to  Jingyue

**Comment by millicentq** [comment]
> -[] @JingyueWu  It is currently under review by Bhavna, the main PI we interface with at Duke. It'll be forwarded to the head investigator once complete.
> -[] @JingyueWu follow up on whether the HIVE team submitted this write-up to Duke, and when/if we will receive this data. -[] @millicentq Please provide a status update to Jingyue
