### ISSUE TITLE
Mazumder - Automate and generate BiosampleMeta data set via Scripts 

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#124]
you know how you guys are pulling information into your two sheets via the APIs (assemblyQC_NCBI & ngs_id_list, respctively)? Could you also do this with our biosampleMeta table? within this you could also have a part of the script that communicates to NCBI to pull info from there as needed? We do capture a decent amount of info in our APIs that could be used to generate that table + it is used to serve as a record anyway? what do you think? -  much of the info is already present in an ncbi format from 1 of the three other core tables (so maybe your script call information from all three APIs depending on the term), then any remaining info can be pulled with the biosample accession for that org from biosample with a script (From Steph)

**Comment by steph-sing** [comment]
Include new entries that were QC'd in ngs and assembly datasets + all current FDA BioProject entries into BiosampleMeta - duplicate to ticket #178

**Comment by HadleyKing** [comment]
Closed with https://github.com/FDA-ARGOS/data.argosdb/issues/143

**Comment by HadleyKing** [comment]
Closed with https://github.com/FDA-ARGOS/data.argosdb/issues/143
