### ISSUE TITLE
Galaxy 22.05 BCOs have malformed URIs

### ISSUE THREAD

**Issue by stephenshank** [FDA-ARGOS/data.argosdb#131]
The [Ebola Sudan BCO](https://data.hyphy.org/web/argos/ebola-reassembly/bco_a03c847bfa9a8077.json) coming from galaxy.hyphy.org (using Galaxy release 22.05) has some malformed URIs, e.g.:

`https://galaxy.hyphy.orghistory_content?history_id=0dd44cc0f0d96662&id=9eed52cc5810c0e6`

A correct one would instead be

`https://galaxy.hyphy.org/api/datasets/318faa28bc2f2134/display?to_ext=fasta`

Two questions that arose were:
1) is this fixed in a later version of 22.05, or in pre-release 22.09?
2) can/should the existing converter script be updated for 22.05 BCOs?

I am currently editing only critical portions by hand, which is messy and will not scale.

**Comment by stephenshank** [comment]
@HadleyKing I'm happy to write an updated converter script. This now appears to be a blocker for #113 and/or #114. I just wanted to pick your brain to see what the status of this is.

**Comment by HadleyKing** [comment]
We will still have to add the filename manually for the time being. That will involve more of a hack of Galaxy code I think. Unless we add to the converter script. Maybe the dataset extension could have an additional object in it that could be parsed into the BCO.
