### ISSUE TITLE
Mazumder - Generate an addition 10 graphs in Observable

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#134]
This work should include write-ups on results and initial conclusions on the standards a given data must meet to be considered 'regulatory-grade'. This work will also help build use cases for DB view + prep for paper. 
- [x] @Jgergely11 Fork all your work into the FDA Argos Collections Observable organized under the Mazumder Lab Observable 
- [x] @JingyueWu suggest updates on all graphs based on current data - get approval from Steph and them implement 
- [ ] @JingyueWu create 4 new graphs in the FDA Argos Collection

**Comment by JingyueWu** [comment]
Status update: I have created a fork of ARGOS NGS QC data exploration notebook and am currently working on recreating the ngsQC graph.

**Comment by steph-sing** [comment]
- [ ] Received Jingyue's initial work
- [ ] Steph email notes below. Considered complete for Dec task list. 
- [ ] Will create a new, more detailed ticket based on these notes for Jan 2023.

____________

(steph)
Please see my comments below per your suggestions - thanks and nice work. Please update new slides in tandem - but do not overwrite Joe's work. Please duplicate the slides in this [QC Visualization Folder](https://drive.google.com/drive/folders/15HU7TpZosIcY1_ekKz8wVdFVMxwpVL3N?usp=sharing), add your initials and the version at the end (i.e. _jw2) for the slide deck name, and then update that slide deck. Please also update any applicable figure legends throughout the slide deck. Please put a link to your new slides in the corresponding GitHub ticket. 

Graph 1 -- In phylogenetic tree, add new organisms and their respective strains (i.e. E.coli, Sudan ebolavirus, and Yersinia)
Table/data used: [ngsQC Organism Tracking](https://docs.google.com/spreadsheets/d/1Nf9Eey2ruwKRkoSMoNhGCAYmFAw2Wb73TzA3sYA3va0/edit?usp=sharing) and [ngsID List, Selection Criteria, and Master Table](https://docs.google.com/spreadsheets/d/1MRQOTr1FaP3_ldbpjUzKUZ6Lf-YvJlILSD1KFu-qMQc/edit?usp=sharing)
- Approve - please also update the file stats on the left side of the slide, and in slide 3. 

Graph 2 -- A series of graphs of average GC content from ngsQC protocol 
Old version: Salmonella enterica, MERS, Influenza A virus, SARS-CoV-2, Marburg marburgvirus, and Monkeypox
Purposed new version: all of the above, plus 1) Yersinia, 2) E.coli, and 3) Sudan ebolavirus
Table/data used: the most recently updated ngsQC_HL (*note: Joe is currently QC'ing Yersinia, and will update in bulk once done) 
- Approve 

Graph 3 -- Average quality score per T, G, C, and A for different organisms
Old version: Average T, G, C, A quality for just Salmonella enterica samples by PacBio RS and PacBio SMRT sequencing platforms
Proposed new version: Generate average T, G, C, A quality for more organisms
- Approve 

Graph 4 -- Dot plot showing average phred score vs. average read length 
Old version: Average phred score vs. average read length for Salmonella enterica and SARS-CoV-2
Proposed new version: Generate average phred score vs. average read length graphs for more organisms 
- Approve

Section 2: New Graphs Proposed by Jingyue

(AssemblyQC)
Not Approved, Comments below in blue: 
X Graph 5 -- Create a bar graph showing the relationships between N50, N75, and N90 with different organisms
Table/data used: the most recently updated assemblyQC_HL
X Graph 6 -- Create a bar graph showing the relationships between L50 and L75 with different organisms
Table/data used: the most recently updated assemblyQC_HL
- Can you explain what type of relationship you are trying to highlight? Comparing the N50, N75 etc. of different Organisms is somewhat meaningless unless they are the same length - these metrics are contextual to the Org it self. Remember, we want these graphs to visually show us the Quality of an assembly. Genome length, number of contigs, GC content, N50, N75, etc. can give us some guidance. Let's try these ideas instead, start simple to give yourself basic insights that can lead to hypothesis building:
a) Average Assembly GC content vs. Org (genus - or break it down further by species)
b) Assembly GC content vs. Length of genome (genus - or break it down further by species)
c) Is there any variation between the length of genomes within a genus or species? So Length vs. all Orgs at the Species level - pick an Org with many entries. Otherwise you could approach from the genus level,  you may have more data that way.
d) Is there any fragmentation? Length vs N50 and N75 per 1 Org  (use our 5 ref Orgs + a few more Orgs, each Org will have it's own graph). From looking at the assemblyQC sheet, there doesn't seem to be any variation between these three metrics, which is making me question the data already. This would be useful to see graphically. 
e) Compare the relevant metrics with in 1 Org? So for Influenza, you have 8 different segments, so compare the GC content of each segment? Are any of these values below what we are expecting and affecting the overall quality of the assembly? Do this for Salmonella and Influenza to start

Graph 7 -- Create a Principal Component Analysis (PCA) plot showing the relationships between % unaligned and different organisms, using different tools (e.g. illumina vs. PacBio)
Table/data used: the most recently updated assemblyQC_HL
- I like this idea, but aim for the species level per Org, and it doesn't have to be a PCA plot. These always look fancy, but it's better to choose the graph that best highlights the data, so be open as you approach this one. I am not sure what to expect here.

Lets come back to these after you complete the NGS and Assembly Graphs:
Graph 8 -- Create a Manhattan plot showing single nucleotide polymorphisms between different biological samples at specific sites of interest. 
Table/data used: the most recently updated siteQC_HL
Graph 9 -- Create a dot plot showing the relationship between mutant variants at targeted position and their corresponding clinical significance

**Comment by steph-sing** [comment]
@JingyueWu can you provide a status update and I will continue this ticket in Jan 2023

**Comment by steph-sing** [comment]
@Jgergely11 please work on updating/generating the Observable graphs based on our current data, and the information I've provided above. Please update/add to your slides and send to me for review by the end of the month. thanks

**Comment by Jgergely11** [comment]
Unlikely to complete 10 new graphs, but will provide at least 2-3.

**Comment by steph-sing** [comment]
@Jgergely11 The new graphs are outlined for Assembly QC above + the updates suggested. Those can all count as new graphs, just FYI

**Comment by Jgergely11** [comment]
https://observablehq.com/collection/@mazumderlab/january-2023-argos-figures

I was unable to complete 10 graphs, but I have added 3 to the link provided above. I started working on the Assembly QC related graphs but those will have to be pushed to February.

The graphs provided are still drafts, but the overall content won't change - I'll just need to make tweaks to labels, axis, etc. 
There is an option to leave comments within the notebooks for any required feedback.

**Comment by steph-sing** [comment]
will review tomorrow, 02/02/223

**Comment by steph-sing** [comment]
@Jgergely11 will use this as a base for the graphs we choose for the QC paper

**Comment by steph-sing** [comment]
Per meeting on 03/24: 

New slides for QC paper (3/24/2023) - (04/07/2023 -   Meet again in 2 weeks
[QC Visualization Folder](https://drive.google.com/drive/folders/15HU7TpZosIcY1_ekKz8wVdFVMxwpVL3N?usp=sharing)
- [ ] Update slide 2, 4, 5, 6, (joe)
- [ ] Update the workflow slide as figure + data model figure (steph) 
- [ ] Update content + subheaders (steph)
- [ ] Reach out to Emily Re: Quast in HIVE vs. Galaxy (metrics) (Joe)

**Comment by steph-sing** [comment]
Items for QC paper were moved to the QC paper ticket. Considering this ticket complete.
