### ISSUE TITLE
QC ~20 Orgs for ngsQC from FDA BioProject (genus level)

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#139]
Joe decided on _Yersinia_ - There are 29 entries, all with assemblies. Its reverse alphabetical order and should be relevant. Approved by Steph. 

Please create a tracking list and place it in this Argos Drive folder: https://drive.google.com/drive/folders/1No1NHbgIoj_YCez59orLXKdhb4i3zFpc?usp=sharing

**Comment by steph-sing** [comment]
@Jgergely11 please give a status update with this ticket in the comments

**Comment by Jgergely11** [comment]
Tracking List:
https://docs.google.com/spreadsheets/d/1Nf9Eey2ruwKRkoSMoNhGCAYmFAw2Wb73TzA3sYA3va0/edit#gid=1003661151

All related SRRs have been loaded into HIVE and QC is in progresss

**Comment by steph-sing** [comment]
This data sheet will be reviewed by me before the v1.41 Dec 21 push. @Jgergely11 please ask me to review and assign me this GitHub ticket once complete. Please notify me by 12pm tomorrow prior to push.

**Comment by Jgergely11** [comment]
[ngsQC_HL](https://docs.google.com/spreadsheets/d/17a9TkNUcuTrfpK6VmfXfXtH0omv046e5E_KGpZ1_Vgs/edit#gid=0) is updated with 10 Yersinia entries

**Comment by steph-sing** [comment]
Received and complete. Included in the V1.41 push.
