### ISSUE TITLE
Marburg genome and proteome + 1 row in 4 QC tables (NGS, Assembly, Biosample, Site + BCOs for all)

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#14]
Rows in 4 tables and new/updated BCOs. Tables and BCOs are lab specific (ngsQC, assemblyQC, siteQC, biosampleMetaData) ; (NGS, Assembly, Biosample, Site + BCOs for all)

**Comment by steph-sing** [comment]
complete
