### ISSUE TITLE
QC ~20 genome assemblies (existing fasta) from the FDA BioProject for assemblyQC (match ngsQC entries)

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#140]
Connected to ticket #139 
- [x] @Jgergely11 please provice @penningtonea a list of associated genome assembly IDs and access to the tracking list you create

**Comment by steph-sing** [comment]
@penningtonea please give a status update with this ticket in the comments, and update the status of the ticket itself

**Comment by penningtonea** [comment]
QC'ing 4 assemblies this week approved by @Jgergely11 :
GCA_002984285.1
GCA_002206495.2
GCA_002983965.1
GCA_002386325.1

**Comment by steph-sing** [comment]
This data sheet will be reviewed by me before the v1.41 Dec 21 push. @penningtonea please ask me to review via comment, and assign me this GitHub ticket once complete. Please notify me by 12pm tomorrow prior to push.

**Comment by penningtonea** [comment]
@steph-sing ready for review

**Comment by steph-sing** [comment]
Salmonella was completed for this ticket. Yersinia will be completed in Jan. Received and complete.
