### ISSUE TITLE
Create draft Assembly workflow documentation and data team training based on Thomas's protocol

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#142]
This should result in the creation of 1 genome assembly + the complete documentation to do so. I want to review your progress in 1 week from today (Dec 12 - even if it is not complete/first draft level) to make sure we are on the right track. Please ping me so I can review your draft protocol next Monday.

**Comment by JingyueWu** [comment]
Plan update: 

I successfully ran de novo assembly on SARS-CoV-2 using MEGAHIT. However, I noticed that the genome assembly can be very versatile in terms of what assembly tool on Galaxy should best be used on what organism. It’s all about optimization and accuracy. I proposed that for now, I come up with a protocol for virus (even though within virus, there are +/- sense; DNA vs. RNA virus etc. but that’s feasible to address in the protocol) and a protocol for bacteria. 

The first complete documentation (i.e. de novo assembly on positive sense RNA virus such as SARS-CoV-2) will be ready for you to review on Monday (12/12). 

Please let me know if you need anything else from me, thanks so much!

**Comment by JingyueWu** [comment]
@steph-sing The [first draft](https://docs.google.com/document/d/1xbuo_12zADdvmBcpfSbl_D4twYAPM6hsWk5LTXQTzXU/edit?usp=sharing) of genome assembly protocol is completed. Thomas and I came up with this _de novo_ workflow for positive sense RNA viruses such as SARS-CoV-2. Please review and provide me with your feedback. Thanks so much.

**Comment by steph-sing** [comment]
@JingyueWu this is a good first draft. I want to read a few papers over the break and review this more critically. I will give feedback in Jan 2023, and you can build out the second draft of this. I am considering this task complete for Dec.
