### ISSUE TITLE
Mazumder - Automate and generate BiosampleMeta data set via Scripts (via APIs- similar to ngs_id_list.tsv generation - OR other Method)

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#143]
Please propose a methodology to Raja after consulting with Dan and others. Once you and Raja agree on how this should be generated, please refer me to your figure or discuss with me so I'm in the loop.

**Comment by HadleyKing** [comment]
#154

**Comment by steph-sing** [comment]
Completed by @kerchner in ticket #151.

**Comment by steph-sing** [comment]
@HadleyKing reopened and assigned to you. If you have questions lets check with Raja before you start. Thanks

**Comment by HadleyKing** [comment]
@steph-sing
I have pushed this table to a branch, made a [PR](https://github.com/FDA-ARGOS/data.argosdb/pull/230) to the dev (v1.3), and assigned you to review the [PR](https://github.com/FDA-ARGOS/data.argosdb/pull/230). 

Your tasks should be (as I see it):
- [ ] Download and review the [table](https://raw.githubusercontent.com/FDA-ARGOS/data.argosdb/a507a55754e1a3f6139d6067e9e5e262839bb630/data_files/biosampleMeta_ncbi.tsv). Link here is for the RAW version. 
- [ ] Provide feedback on the table in the [PR review](https://github.com/FDA-ARGOS/data.argosdb/pull/230) 
- [ ] Once all items are resolved for your review we will merge into dev branch.

**Comment by steph-sing** [comment]
@HadleyKing please Merge to Main

**Comment by steph-sing** [comment]
@HadleyKing can I close this ticket?
