### ISSUE TITLE
Mazumder - Update assemblyQC_ncbi table with all FDA BioProject assemblies

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#145]
You have already done this through this sheet https://data.argosdb.org/ARGOS_000010 - please update the BCO language (title, usability domain, etc.), file name, and IO Domain) + update the file as necessary with the Data dictionary (though I believe it already conforms to the non-core data dictionary). If you want to update it per the core data dictionary, let me know and we can plan those updates.

**Comment by steph-sing** [comment]
for more clarity - your new sheet will essentially be this, plus and unique entries that we have completed outside of the FDA bioproject (not that many)

**Comment by steph-sing** [comment]
Was not complete before V1.41 data push for Dec 2022.

**Comment by HadleyKing** [comment]
- Data file is here: https://raw.githubusercontent.com/FDA-ARGOS/data.argosdb/v1.2/data_files/assemblyQC_ncbi_all.tsv

- [ARGOS_000010/DRAFT](https://biocomputeobject.org/builder/https/biocomputeobject.org/ARGOS_000010/DRAFT) has been updated and is ready for review.

**Comment by steph-sing** [comment]
@HadleyKing please input the new file here: https://github.com/FDA-ARGOS/data.argosdb/tree/main/data_files - so that I can review and download the file. If not main, then under an up-to-date tag as a pre-release. Other Files in Main need to be updated as well, but we'll leave that for another ticket. 

BCO Errors/Issues:
- [ ] You technically have the updated BCO info for this dataset in Argos_000038, too. I referenced BCO ARGOS_000010 because you essentially needed to fix/combine the work and datasets conducted in each BCO into one. But it is your choice which BCO you would like to use and update. I can retire either of them once you decided, update, and complete the work. Otherwise, necessary updates to the BCO you linked above are outlined below: 
- [ ] 
- [ ] Title of BCO does not correspond to the dataset or use case of the table, Please correct. current title: BioSample Metadata from the Original FDA BioProject in NCBI.
- [ ]  Both lines in the Usability domain also need to be updated to reflect the dataset and the use cases.
- [ ] Key words need to be corrected. Please update.
- [ ] Environmental variables are required in the BCO per the BCO Team's directives. Please add. 
- [ ] Output subdomain: The file name is incorrect for this work (should be assemblyQC_ncbi.tsv) and the file listed in the Output Subdomain URI is incorrect and does not match - this will throw an error in the server.

**Comment by steph-sing** [comment]
This BCO could also be updated and reused for the BioSample sheet, and I don't have to retired it. FDA BioProject: Assembly, NGS, and BioSample should all be separate data sets and have BCOs. You can reference all current BCOs, Here: https://docs.google.com/spreadsheets/d/1uA21djJrp0Y8ZQdzlpqsWmWrCn-8EAzaL5JAUatKjMY/edit?usp=sharing

**Comment by HadleyKing** [comment]
- I would prefer to use [ARGOS_000038/DRAFT](https://biocomputeobject.org/builder/https/biocomputeobject.org/ARGOS_000038/DRAFT)
- [data.argosdb/v1.2/data_files/assemblyQC_ncbi_all.tsv](https://raw.githubusercontent.com/FDA-ARGOS/data.argosdb/v1.2/data_files/assemblyQC_ncbi_all.tsv) is the current `dev` branch, which will become permalink for the release once it is published. 

I will update [ARGOS_000038/DRAFT](https://biocomputeobject.org/builder/https/biocomputeobject.org/ARGOS_000038/DRAFT) to reflect your requests.

**Comment by steph-sing** [comment]
@HadleyKing can you please put the file in that space you created above so I can download and review the file? Thanks

**Comment by steph-sing** [comment]
Completed as part of 1.42 data release.
