### ISSUE TITLE
Crandall - Update seqSight for use in ngsQC protocol

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#148]

**Comment by steph-sing** [comment]
please provide a status update for this ticket

**Comment by kacrandall** [comment]
Xinyang will run a Salmonella and an E. coli SRA set through seqSight to align reads to both human and bacterial references. seqSight will output #reads, %reads mapped to TaxonIDs. We hope this might be useful as QC for NGS data. We'll give it a test and see what the outputs look like and have some results to discuss by the end of March 2023. Keith and Xinyang are working on this.

**Comment by steph-sing** [comment]
Excellent - excited to see the results and how we can incorporate these new QC values.

**Comment by steph-sing** [comment]
Moving this to continue on the April Task list.

**Comment by steph-sing** [comment]
@kacrandall any movement on this task?

**Comment by penningtonea** [comment]
Move to July task list

**Comment by steph-sing** [comment]
@kacrandall Any updates for this item? I may put it in the backlog unless you plan to continue this in August

**Comment by kacrandall** [comment]
All the requested data have now been uploaded into the system. Our tasks are complete.
