### ISSUE TITLE
Crandall - QC ~20 Orgs for ngsQC from FDA BioProject (genus level)

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#150]
- Ticket #149 will depends on your SRR selection for this task. 
- Please coordinate with @Jgergely11 while making your SRR selection 
- You can use this dataset to guide you https://data.argosdb.org/ARGOS_000009

**Comment by steph-sing** [comment]
@Keillyzhang please provide a status update

**Comment by Keillyzhang** [comment]
Tracking List:
https://docs.google.com/spreadsheets/d/1UDhf5M8seO0htlObwaWBoPQvgzPc2-CnrW-kYc8VI8E/edit#gid=509357166

All related SRRs have been loaded into HIVE and QC is in progress

**Comment by steph-sing** [comment]
Will continue this Task into Jan 2023

**Comment by steph-sing** [comment]
Duplicate to ticket #177 - closing ticket
