### ISSUE TITLE
Mazumder - Create list of FDA BioProject SRRs without associates genome assemblies

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#152]

**Comment by steph-sing** [comment]
Based on the tables created by @HadleyKing in tickets #144 and #145, I will re-assess this task using data from those tables, where the through-line is the FDA ARGOS ID in each sheet. I will run my R script with this new data and double check the list, then provide to the team. I will also commit my R script to this repo once finished.

**Comment by steph-sing** [comment]
will run updated script on Monday Feb 27.

**Comment by cwoodside1278** [comment]
AssemblyQC_HIVE? Check this

**Comment by cwoodside1278** [comment]
Comment from Raja: "Is there a place on ARGOSdb where I can find a list of read accessions that do not have assemblies associated with them?" 

Once you get this number slack them to both Raja and I.

**Comment by cwoodside1278** [comment]
Joe: Right now I’m getting 341 Argos bisamples that don’t have an associated assembly. I’ll do some more verification, but my building lost power about an hour ago so I’m not sure when Ill be able to get a final number

**Comment by cwoodside1278** [comment]
There are 168 SRRs that do not have associated assemblies listed on argosDB. If filtering for only the FDA Argos Bioproject (PRJNA231221) that number drops to 22 SRRs. These values are not explicitly listed, but can be found by filtering the ngsQC table (I used schema version 1.5 which I believe is the most recent version published)
[3:00 PM] If the question was to find the number of SRRs (or the associated Biosamples) for the entire Argos project that number will be significantly larger, but I'm not sure if that is what is being requested.

**Comment by cwoodside1278** [comment]
@Jgergely11 updates?

**Comment by Jgergely11** [comment]
"PRJNA231221_stats.csv" and "PRJNA231221_biosample_assembly.csv" have been added to data.argosdb/data_files. 
219 of the 1629 ARGOS biosamples do not have an associated assembly.

**Comment by cwoodside1278** [comment]
Could you provide a list of which ones do not? Maybe in a Google Sheet? @Jgergely11 Once you're done can you close this task. Thank you!!!!

**Comment by Jgergely11** [comment]
"PRJNA231221_biosample_assembly.csv" has that information.
