### ISSUE TITLE
Push V1.1 Data dictionary to GitHub

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#158]
sheets are available in the server or in the google drive

**Comment by HadleyKing** [comment]
@steph-sing 
I got the following errors and made the changes listed below each one:
  - Error! genomic_coordinate_start at row 88 is not defined in data_dictionary/v1.1/property_definition.tsv. Exiting.
  	- changed genomic_coordinate_start to genomic_coordinates_start in core sheet

  - Error! reads_unaligned at row 15 is not defined in data_dictionary/v1.1/property_definition.tsv. Exiting.
    - Removed reads_unaligned in non core sheet
  - Error! level at row 20 is not defined in data_dictionary/v1.1/property_definition.tsv. Exiting.
    - Removed level in non core sheet
  - Error! gc_content at row 19 is not defined in data_dictionary/v1.1/property_definition.tsv. Exiting.
    - Removed gc_content in non core sheet

**Comment by steph-sing** [comment]
Thanks for the error log. 
we may get an error while pushing from 'genomic_coordinates_start' - this one has for some reason been weird before. Just and fyi. 
links were included in FDa meeting slides
@steph-sing will update releases notes in GitHub
