### ISSUE TITLE
Update biosampleMeta with all Orgs completed in tickets #139 and #140

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#159]
Update biosampleMeta with All Orgs completed by Joe and Emily in tickets #139 and #140 respectively, you can also use this sheet [NGS and Assembly Org Tracker](https://docs.google.com/spreadsheets/d/1Nf9Eey2ruwKRkoSMoNhGCAYmFAw2Wb73TzA3sYA3va0/edit?usp=sharing)

Once complete and reviewed by Joe, Reassign this ticket to me for review and download for the V1.41 data push.

**Comment by JingyueWu** [comment]
@steph-sing I have completed this task and Joe has reviewed it. Please [review](https://github.com/FDA-ARGOS/data.argosdb/issues/159) for the V1.41 data push, and let me know if you have any questions for me. Thanks!

**Comment by steph-sing** [comment]
Received and complete.
