### ISSUE TITLE
Crandall - Add arguments to `biosample_complete.sh` to pass `bco_id` and `schema_version`

### ISSUE THREAD

**Issue by kerchner** [FDA-ARGOS/data.argosdb#161]
Enhancement to #151 ; currently `bco_id` and `schema_version` must be filled in manually

**Comment by kerchner** [comment]
@steph-sing This enhancement to the code has **_not_** yet been completed.

**Comment by steph-sing** [comment]
My mistake. I will reopen the ticket and move it back to In Progress.
