### ISSUE TITLE
Mazumder - Select 5-10 SARS-CoV-2 XBB for ngsQC - then select 1-3 SRR files for Assembly Protocol

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#165]
Joe 1) The first step is filtering NGS runs using NCBI filter options to get potentially high quality runs. In some cases we might get 100s of runs. Then we should pick the top 3. Top 3 can be determined based on completeness of metadata or earliest submission.

Joe 2) Run ngsQC on a selected set of SRR data. These data are chosen based on certain criteria (we choose these based on our knowledge, and these are documented)

Joe 3) Choose the set of SRR data that we wish to use for assembly of this variant based on certain QC metrics (let's say, starting with 3-5 key ngsQC metrics that provide an overview of the quality of sequencing data (we can already make some basic assumptions based on Joe's initial Observable graphs) - and let's say we choose 1-3 paired end files to move to the assembly stage - all of this is also documentented)

Jingyue 4) We apply the Sars-Cov-2 draft assembly protocol that Thomas developed, and Jingyue has developed into a draft written protocol

Emily 5) Run generated fasta(s) through the AssemblyQC protocol and collect metrics 
 
Joe, Jingyue, Emily, Steph 6) Collect entire process in BCO under the unique BCO ID using the ARG_ prefix 

Deliverables would be:
- 5-7 slides that outline the process, selection criteria at each stage, and graphs of the assembly results
- 1-3 fasta files for XXB 
- additional documentation of processes and protocols
- assemblyQC metrics collected
- BCO with Unique ID generated 

Steph will review at each step

**Comment by steph-sing** [comment]
This Task cannot be complete due to lack of XBB.1.5 fastq data. We will keep an eye out for any incoming data in NCBI. Until then we will prioritize other tasks.

@Jgergely11 Please provide a summary email to Raja as to why this can't be complete, and propose alternative work. Please CC me, Jingyue, and Emily in that email. Thanks

**Comment by Jgergely11** [comment]
I reached out to NCBI about the paired end issue with the XBB.1.5 and was informed that they will be re-uploaded. Still waiting on clarification if they we be re-uploaded as paired-end, or will be designated as single end reads. I will update when I receive further information.

**Comment by steph-sing** [comment]
Moving into Feb 2023 Task list
