### ISSUE TITLE
Mazumder - Optimize second draft of SARS-CoV-2 Assembly Protocol resulting in 1 fasta

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#174]
Links to documentation: https://drive.google.com/drive/folders/1O5pq5cw4w8iNeGuKyS8-ES44juf6zFGd?usp=sharing

**Comment by steph-sing** [comment]
In both Galaxy and HICE (two different protocols)
List of HIVE assemblers:
[De Novo Sequence Assemblers](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=menu&root=Portal&selected=De_Novo_Sequence_Assemblers)
[Canu](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-canu)
[Contig Extension](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-hiveseq&cmdMode=hs-contigextension)
[IDBA-HYBRID](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-pipeline-idba-hybrid)
[IDBA-UD](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-pipeline-idba-ud)
[PRICE](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-price)
[SPAdes](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-spades)
[Velvet ( Paired-End )](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-velvet-paired)
[Velvet ( Single-End )](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-velvet-single)

**Comment by steph-sing** [comment]
Connected to tickets #112 #185 #186

**Comment by JingyueWu** [comment]
Status update: currently modifying the initial _de novo_ assembly protocol and drafting the reference-guided assembly protocol (workflow involves Hexagon/Heptagon in HIVE and Stanford SARS-CoV-2 QC platform). Will finish the draft by the end of the week (1/27).

**Comment by steph-sing** [comment]
Please post links to the drafts here by Friday - please don't focus on formatting right now. Bullet points, sub bullet points, and snap shots (where necessary) are perfectly fine for a draft. thanks

**Comment by JingyueWu** [comment]
@steph-sing Please review the very first draft of the protocol of both _de novo_ and reference-guided assembly: https://docs.google.com/document/d/1Yw9jQFPWVqIvhjLV_9xfl0vJmj85tXTNoA4S202mUaM/edit?usp=sharing

**Comment by steph-sing** [comment]
@JingyueWu thank you . I will review today and get back to you with feedback on the google doc, if necessary.

**Comment by steph-sing** [comment]
Complete. Will build on these protocols in Feb 2023.
