### ISSUE TITLE
Mazumder - Research and collect Orgs of interest 2x per month

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#179]
Orgs should be logged herer, and then approved by Raja and/or Steph: https://docs.google.com/spreadsheets/d/1KD4WfihfcFzy9MCcmyvgkIlyy2hGmq9vtxYFW5SG4RM/edit#gid=0

schedule a 15 min meeting 2x per month with each other to go over your findings prior to getting approval.

**Comment by JingyueWu** [comment]
Status update: Our first meeting was scheduled by Emily on Wednesday (1/25) at 2 pm after the collaborators' meeting. 

Document: [Pending Organisms Log](https://docs.google.com/spreadsheets/d/1KD4WfihfcFzy9MCcmyvgkIlyy2hGmq9vtxYFW5SG4RM/edit?usp=sharing)

**Comment by steph-sing** [comment]
Completed by Steph, Emily, and Jingyue.

**Comment by steph-sing** [comment]
Complete
