### ISSUE TITLE
Mazumder - Check frameshift and stop codon in Mazumder Lab's SARS-CoV-2 assemblies

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#182]
1. QC the 2 SARS-CoV-2 assemblies that we have (GCF_009858895.2 and GCA_009858895.3) on Stanford's CoVDB
2. Based on the output, grasp the number of frameshift and stop codon

Expected date of deliverable: EOD Friday (1/13/2023)

**Comment by steph-sing** [comment]
Reviewed by @steph-sing.  Complete.
