### ISSUE TITLE
Mazumder - Add 2 new columns to SARS-CoV-2 assemblyQC 

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#183]
For SARS-CoV-2 assemblyQC table, please add column 1) number of frameshift and 2) number of stop codons (i.e. Gene | Number of Frameshift | Number of Stop Codon). In addition, values allowed are 0 to 1000 or leave the cell empty.

Please check with Raja for others that are potentially worth considering. Please also wait until Jingyue finishes #182

**Comment by steph-sing** [comment]
Complete. Gene was left out per Raja's recommendation.
