### ISSUE TITLE
Mazumder - Perform Genome Assembly Using HIVE's Assemblers

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#185]
1. Perform genome assembly on SRR14460626 (B.1.351) using HIVE SPAdes, 
2. QC the output contig in Stanford platform
3. Compare the results with MEGAHIT and metaviralSPAdes in Galaxy

**Comment by steph-sing** [comment]
1. This is the list of assemblers we have on HIVE: 

[De Novo Sequence Assemblers](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=menu&root=Portal&selected=De_Novo_Sequence_Assemblers)
[Canu](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-canu)
[Contig Extension](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-hiveseq&cmdMode=hs-contigextension)
[IDBA-HYBRID](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-pipeline-idba-hybrid)
[IDBA-UD](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-pipeline-idba-ud)
[PRICE](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-price)
[SPAdes](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-spades)
[Velvet ( Paired-End )](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-velvet-paired)
[Velvet ( Single-End )](https://hive.biochemistry.gwu.edu/dna.cgi?cmd=dna-velvet-single)

**Comment by JingyueWu** [comment]
Feedback for genome assembly on SRR14460626 (B.1.351) using HIVE SPAdes: 

1. The output FASTA file that HIVE SPAdes generated contains 5 contigs; the largest one has 22302 nucleotide, which is ~74% of the reference (22302/29903)

2. The QC result on Stanford platform shows a list of missing genes: 

<img width="1378" alt="Screen Shot 2023-01-18 at 11 57 37 AM" src="https://user-images.githubusercontent.com/61590108/213282961-d36560be-e4db-43d8-a3b9-dfd345c28595.png">

3. The good news is that HIVE SPAdes runs genome assembly pretty fast -- much faster than both assemblers on Galaxy which makes sense, as Hadley said Galaxy is available to the general public. 

So far, based on the "grading system" in my mind, for SRR14460626 (B.1.351) at least, I would rank HIVE SPAdes as #1 as compare to MEGAHIT and metaviralSPAdes on Galaxy, it still produced relatively long contig and the QC results suggested fewer missing genes.

**Comment by JingyueWu** [comment]
Currently running genome assembly on SARS-CoV-2 Wuhan-Hu-1 using HIVE SPAdes

**Comment by JingyueWu** [comment]
See #174

**Comment by steph-sing** [comment]
This task will technically be considered on-going. but I will make a new, more specific task. This task is considered complete for Jan 2023.
