### ISSUE TITLE
Pond - Share XBB.1.5. SARS-CoV-2 NCBI list with Mazumder Team

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#187]
Share list with @Jgergely11 and @steph-sing. 
- [ ]  @Jgergely11 will filter the list for accessions links to fastq files, which can be run through our respective ngsQC protocols, can be used to build new assemblies, and we can run the fasta's through our assemblyQC protocol. 
- [ ] @Jgergely11 and @stephenshank can annotate the list to track which accessions have fastq data

Once we have an idea of how much data we're working with, we can come up with a plan to QC/assemble new genomes.

**Comment by stephenshank** [comment]
@Jgergely11 The [list of GISAID accessions and corresponding SRA accessions is here](https://data.hyphy.org/web/argos/harmonized-xbb_1_5.csv). I also have a FASTA with genomes corresponding to the GISAID  accessions that I can share privately (they are pretty sensitive about others sharing the data publicly).

**Comment by steph-sing** [comment]
Complete - Share annotated list when ready
