### ISSUE TITLE
Mazumder - Run SRR14460626 on Pegasus Using SPAdes

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#189]
- [x] Request access to HPC by submitting account request form
- [x] Set up public SSH key and log in my account
- [x] Meet with Pat on Wednesday and Thursday to submit the assembly job on SRR14460626 (through MEGAHIT, SPAdes, or through Canu, quest, and Velvet)
- [ ] Send Dr. Mazumder the output FASTA file

**Comment by JingyueWu** [comment]
A couple of updates:

1. According to Pat and I's knowledge, SPAdes does not exist on Pegasus. After logging in my Pegasus account through GW HPC and typing the command ml available, hundreds of tools show up alphabetically as a list, yet SPAdes is not found. However, some of the assembly tools that Adam mentioned in the above email are available on Pegasus (i.e. Canu, quast, and Velvet); 

2. Pat and I will meet on Wednesday and Thursday to get the job submitted on Pegasus through Slurm, which is a job scheduler tool on Pegasus.

Adam did say that the RT folks can install MEGAHIT if we want, so my understanding is that SPAdes can also be installed, but by them not Pat or I. Thus, moving forward, I purpose that A) request RT folks to install MEGAHIT and SPAdes as those are the two assemblers I have tried and were proven to be good, or B) try running assembly on the 3 available assemblers (i.e. Canu, quast, and Velvet) on Pegasus. 

Please let me know your thoughts and feedback. If we go with B), then Pat and I can get the assembly job submitted on Pegasus by the end of this Thursday.

**Comment by JingyueWu** [comment]
Status update: 

- [ ] @JingyueWu Email Adam to install MEGAHIT and SPAdes (with cc to Dr. Mazumder and Pat) (*#1 priority)
- [ ] @JingyueWu Work with Adam (or Pat) to submit SRR14460626 and Wuhan-Hu-1 on Wednesday and Thursday on Pegasus through Slurm
- [ ] @JingyueWu If the above is successfully done, then try running Wuhan-Hu-1 along with SRR 626 on Canu, quast, and Velvet.

**Comment by JingyueWu** [comment]
Status update: SRR14460626 job submitted using SPAdes through Slurm on Pegasus. I checked before the end of the day today and found that the job has completed in the GW HPC queue. I will provide an update with the group tomorrow (1/31) morning.

**Comment by steph-sing** [comment]
@JingyueWu please provide status

**Comment by steph-sing** [comment]
Marking as complete
