### ISSUE TITLE
Mazumder - Perform Reference-Guided Genome Assembly using Wuhan as reference in HIVE

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#193]
Perform reference-guided assembly on SRR22935892 SRR22935236 SRR22934993 in HIVE. No need to annotate interesting sections on alignments. Finish by Tuesday (1/31). 

- [ ] Download Textpad and ClustalX (http://www.clustal.org/download/current/ the file is clustalx-2.1-win.msi).

- [ ] In ClustalX go to File -> Save sequences as -> Select ClustalW sequence number "On" -> save. This will print sequence position numbers

- [ ] Go to microsoft word and paste just the sequence blocks that have deletion/insertion there -> select all -> Courier New font 7 (will allow you to see the sequences better) -> change margin to 0.5 in (see attachment to understand how it should look like)

- [ ] QC for frameshift and stop codons all three assemblies using Stanford tool to some annotations about gene names etc about the deletions or frameshifts

**Comment by steph-sing** [comment]
Moving into Feb 2023 Task list

**Comment by steph-sing** [comment]
Marking as Complete
