### ISSUE TITLE
Crandall - Update biosampleMeta tsv to conform with schema v1.2 if needed

### ISSUE THREAD

**Issue by kerchner** [FDA-ARGOS/data.argosdb#196]
Confirm that tsv created by `lib/biosample_complete.sh` conforms to schema v1.2.  Make changes if needed.

**Comment by steph-sing** [comment]
Completed and included in v1.42 data release.

**Comment by kerchner** [comment]
This also needs to be reopened (sorry!).  The data set referenced above included some manual edits by @penningtonea .  However, those edits provide helpful information for me in implementing this ticket.

**Comment by steph-sing** [comment]
@kerchner I updated this table for you. In my mind this task is complete. We can open a fresh ticket for Feb 2023 task list if needed.
