### ISSUE TITLE
1st draft of BCO review criteria and process documentaion 

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#20]
- Steph started document to hold ideas:
https://docs.google.com/document/d/15FpGg8sihp047CG3ifIqqlrMqeE0zWlizX9guPSTSIk/edit
- Example BCO template sheet https://docs.google.com/spreadsheets/d/1_q7EQ2SrGwuaLzWPE21o4XNu0wzgooOdYDcimo60Hlc/edit?pli=1#gid=1864504313
- KB_BCO DOC: https://docs.google.com/document/d/1Jng0Mh0MggbuA0hi23ZysyldcjsgvPbkXWSTmaZ1yLc/edit
- BCO Documentation: https://docs.biocomputeobject.org/user_guide/

**Comment by steph-sing** [comment]
complete
