### ISSUE TITLE
Mazumder - Optimize scripts to QC data in Core datasets based on the data dictionary 

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#200]
Optimize scripts to QC data in the data in Core datasets based on the data dictionary

**Comment by steph-sing** [comment]
This task is dependent on task #207 and this work is still ongoing - will move to March tasks

**Comment by cwoodside1278** [comment]
@HadleyKing is this still open?

**Comment by cwoodside1278** [comment]
Get all HIVE3 data published on data.argos.db.

**Comment by cwoodside1278** [comment]
Hadley said to close. It is no longer applicable.
