### ISSUE TITLE
Mazumder - Run Error Testing on the Data Dictionary V1.2 + Release V1.2 data dictionary to GitHub

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#201]
Run Error Testing on the Data Dictionary V1.2 + Release V1.2 data dictionary to GitHub

**Comment by HadleyKing** [comment]
266daa2f980fa6fd6ae3704edf57ccc69d2ba673

**Comment by steph-sing** [comment]
Complete 
https://github.com/FDA-ARGOS/data.argosdb/tree/v1.2/tests/v1.2/test_results
https://github.com/FDA-ARGOS/data.argosdb/tree/v1.2/data_dictionary/v1.2
