### ISSUE TITLE
Mazumder - Implement DB changed (applies to Argos and GlyGen)

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#208]
Sub-tickets will be made in this ticket for Robel, then converted to issues. 
Changes noted and approved [HERE](https://docs.google.com/document/d/1vQo8GeIBC7XuV-P4mtGYLsOI9pDptPmoSEjx5SZnJdU/edit?usp=sharing)

**Comment by steph-sing** [comment]
Per Meeting on 2/24:
- Use MockUps from a few months ago to update the selected search criteria for Robel's tickets
- Use BCOs and data body to selecting searches and filtering 
- Send MockUps to @jeet-vora for review and input by COB Tuesday Feb 28th
- Present MockUps to Robel in the All Hands meeting on Friday March 3

**Comment by steph-sing** [comment]
Link to Mock ups here: https://docs.google.com/presentation/d/1ddx0OyN7fs-vexixtngCBSbGyz4FfChz/edit?usp=sharing&ouid=101713086141465545921&rtpof=true&sd=true

**Comment by steph-sing** [comment]
@rajamazumder @rykahsay 

Use these update Mock Ups to update data.argosdb: [Database Interface Mock UPs](https://docs.google.com/presentation/d/1ft0SSb5sg7pJ9u8w6sbpGFs3ixNUjhpAJBLqrjg6Lho/edit#slide=id.g21515c23794_0_6)

**Comment by steph-sing** [comment]
Hi @rykahsay - Were you able to access the link above and do you need any additional info from me or Raja?

**Comment by rykahsay** [comment]
Please have a look at :
https://data.tst.glygen.org/
https://beta-data.glygen.org/

**Comment by steph-sing** [comment]
@rykahsay @rajamazumder 

**Bug comments:** 
- the FAQ and Release History pages do not seem to be functioning in GlyGen Tst/Beta

**Argos/GlyGen Applicable comments:** I agree with the look, feel, and functionality of the Tst page but have a few recommendations/comments:
1) Recommendation: I would explain the difference between 'dataset metadata' and 'dataset body' in the FAQs, or information bubbles on the search page 

2) Functionality Issue: When selecting either 'dataset body' or 'dataset metadata' and typing 'sars' in the search box, the same results return for both selections. As a user, I would assume these would return different results, where a) 'dataset body' pulls from the BCO information (i.e. in ARGOS =  species, priority, tag, file name, status, scope, and molecule) and it would give you a list of BCOs that fall into that search category (current search return view). Where as b) 'dataset metadata' would primarily return a list of datasets that the search criteria were present in, maybe even with the potential of selecting the line(s) of data in the datasets in the Sample View. Essentially, I'm not sure I fully understand how or how well the 'dataset metadata' filter is functioning, or even how best to test this. Maybe it would help to discuss this part in more depth. 

3) Recommendation: rather than have a link that says 'view details...' in the search list, I would make either the BCO or the dataset file selectable from the search page. Where as the 'view details' selection could lead you to the information compiled under 'Release History' and/or 'History Detail' per that BCO/dataset 

4) Recommendation: Have BCOs show up consecutively in the list on the search page 

5) Request: I like the link to the API page - Requesting to have this added to the ARGOS page 

6) Request: The ability to Archive certain datasets/Cards/BCOs and have a) this to be reflected in the Release History and, b) be able to access Archived datasets/Cards/BCOs in the DB via a tab

**Comment by steph-sing** [comment]
### **Comments after meeting on 5/17**

Bugs:

- [ ] When selecting filters in the side bar, the numbers reflected in each category do not adjust to the currently available selection based on the current filters being applied 
Example: after selecting Datasets Body, searching 'Kinase' in the search bar, and selecting Homo sapiens in the filters (which shows a list of 48 files), other #'s next to the filtering options did not adjust to the current search criteria. For example,  the # of CSVs or Reviewed datasets remains the same and out numbers the list of 48 files 
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/48079325-3170-408c-8292-8d3209d06b83)

- [ ] search bar does return results for a specific BCO name or BCO file name under either choice of Dataset Body/Dataset Metadata
Example: BCO name: Human O-GlcNAc Glycosylation Citations (O-GlcNAc Atlas); File Name:human_proteoform_citations_glycosylation_sites_oglcnac_atlas.csv 
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/c5d82a53-7391-4542-9ae8-406282ae29b1)
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/6418279e-3d87-4855-95f3-b973fa59bd55)
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/63a7558a-4124-4c9d-bab2-8eb44dee9085)

- [ ] No option to return to a previous page:
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/6e74f52a-d6eb-4fe6-8963-b25ee11f9ce9)

- [ ] Cannot easily reset filters. No 'Reset All', 'Remove All', or 'Apply All' function 
- [ ] Recommendation: I would explain the difference between 'dataset metadata' and 'dataset body' in the FAQs, or information bubbles on the search page

**Comment by steph-sing** [comment]
@jeet-vora Please add your bugs/comments

**Comment by jeet-vora** [comment]
@steph-sing I have merged my comments and issue with your comments above. We now have all the issues reported in the comment that we discussed yesterday.

**Comment by steph-sing** [comment]
Thank you @jeet-vora - We can present/discuss during the Friday meeting. I will notify Hadley. Thanks

**Comment by jeet-vora** [comment]
@rykahsay Please take a look at the comments above - https://github.com/FDA-ARGOS/data.argosdb/issues/208#issuecomment-1553342315

**Comment by rykahsay** [comment]
@jeet-vora @steph-sing -- having all the issues on one ticket is not easy to track. Please make separate ticket/issue for each of the issues and I can try to address them separately

**Comment by jeet-vora** [comment]
Sepearate tickets created from the [comment](https://github.com/FDA-ARGOS/data.argosdb/issues/208#issuecomment-1553342315). Added @steph-sing to track

1. #302 
2. #303 
3. #304 
4. #305 
5. #306 
6. #307

**Comment by steph-sing** [comment]
broken out into smaller tickets - closing this ticket
