### ISSUE TITLE
Mazumder - At least three genome assemblies to completion (released to the DB with BCOs)

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#212]
Protocol development and optimization will happen in tandem. 
Please put links to your protocols in this ticket.
Connected to ticket #213 

Current Genome Assemblies (in progress): 2 XBB.1.5
@JingyueWu Please provide a status update on these two: 

New Orgs for Feb will include selections of Marburg, circulating Influenza (H3N2, H1N1), and potentially RSV. @Jgergely11 will provide this data to you (SRR + associated genome assemblies - potentially just one or the other depending on availability). 
Once we have direction from Joe, I will show you how to make a sub-ticket within this ticket for additional tasks.

**Comment by Jgergely11** [comment]
@JingyueWu  Please complete de novo and reference guided assemblies for the samples listed below. They can also be found here [FDA_BioProject_Orgs_W/O_GenomeAssembly](https://docs.google.com/spreadsheets/d/1Nf9Eey2ruwKRkoSMoNhGCAYmFAw2Wb73TzA3sYA3va0/edit#gid=453349699) where you will notice that you have been designated as the assignee. 

- [ ] Marburg marburgvirus -	IRF0296 MARV MUSOKE - SRR17262090
- [ ] Marburg marburgvirus -	Ravn virus/IRF0322 RAVN - SRR17262091
- [ ] Marburg marburgvirus -	Musoke -                  	SRR10027406
- [ ] Marburg marburgvirus -	IRF0328 MARV CI67 - SRR17261988
- [ ] Marburg marburgvirus -	IRF0202 MARV ANGOLA - SRR17262089

**Comment by JingyueWu** [comment]
Reference genome accession: NC_001608.3

All de novo and reference-guided Marburg assemblies have been shared with Stephanie and Emily via email.
