### ISSUE TITLE
Mazumder - Make QC data available via HIVE APIs

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#221]
Identify the QC tables: ngsQC, assemblyQC, siteQC, biosampleMeta

Objectives:
1) Make HIVE 2 data available from HIVE 3 - HIVE Packs?
2) Run HIVE 2 data through HIVE 3 Protocols 
3) We need the same level of documentation in HIVE from Pat/Jonathon like [api.argosdb.org](http://api.argosdb.org/) with examples etc.
4) Jonathon and Pat should talk to Vahan prior to meeting with Raja (Jonathon can also speak with Anton)

Potential Blockers:
- Protocols are not identical - inputs are the same, outputs are not the same. Prioritize running HIVE 2 data in HIVE 3
- HIVE APIs/Data model issues?

**Comment by kee007ney** [comment]
Built dropboxes in HIVE3, but data transfer does not initiate. Waiting for a meeting with Vahan (after his recovery?) to troubleshoot.

Need a little more info on the specific data to be pulled. Will follow up by email.

**Comment by steph-sing** [comment]
Not Complete for Feb Task list. Will move to March and assign as backlog.

**Comment by kee007ney** [comment]
@pmcneely: ETA April 20th

**Comment by pmcneely** [comment]
Will have a look into this as I'm able. The best thing to do will be to get the API calls built into HIVE-3, and getting a shim in place will take a significant investment of time separately from the API itself.

**Comment by kee007ney** [comment]
Based on our conversation today:

1. For every org in list that Stephanie provides:
2. Pull all data from data.argosdb.org
~~3. Reformat into HIVE3 schema~~
4. Post to HIVE3

This is strictly to build the API to move data
Next step is to reformat data (in between steps 2 and 3) to be in the HIVE3 schema format.

**Comment by steph-sing** [comment]
@kee007ney @pmcneely @penningtonea I have updated the API query documentation. I have added examples for queries in the beginning of the doc, links to the HIVE 3 JSON outputs, and updated the detailed response bodies. Hopefully this is more helpful, but please let me know if you need any other information from me. Thanks 
Link: [ARGOS Documentation: API Queries and JSON Outputs](https://docs.google.com/document/d/1BSJjQk_sXUZKDhiw6wtMRbE6S319g5Qwoz9ixTuK51Y/edit?usp=sharing)

**Comment by pmcneely** [comment]
I'll echo "on hold until you have the Betsy Deployment taken care of" - @kee007ney is working through deployment, with my assistance as needed.

**Comment by kee007ney** [comment]
My current understanding of our workflow:
Part 1:
Use the "search" API endpoint to get everything in a table (use the BCO ID).
Get all tables from data.argosdb.org (I count 13 currently).
(Probably a shell script with 13 curl commands, output each to a different file)

Part 2:
Push all 13 files to HIVE 3 using its API, use argos@argos.org credentials.

**Comment by steph-sing** [comment]
@kee007ney this sounds right to me aside from the dataset count. I would start with just the following datasets and BCOs since they are the only protocols/datasets derived from HIVE (let me know if I need to update the API documentation again). These are also our CORE QC datasets:

ARGOS_000011	siteQC_HIVE.tsv
ARGOS_000012	assemblyQC_HIVE.tsv
ARGOS_000019	ngsQC_HIVE.tsv
ARGOS_000020	biosampleMeta_HIVE.tsv



you may also need this one (mapping dataset):

ARGOS_000018	ngs_id_list.tsv

**Comment by kee007ney** [comment]
Has there been a change to the API? I'm no longer seeing the same API endpoints, and the page now says "GlyGen Dataset APIs"

https://api.argosdb.org/

**Comment by steph-sing** [comment]
@rykahsay Looks like the APIs are reflecting GlyGen and we believe this to be an error. Can you address:
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/2fb6c6d8-abe6-4df2-ba69-5c9b2e8f9f9f)

**Comment by rykahsay** [comment]
API header fixed:
<img width="596" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/ff498ded-d5d1-4a86-806f-423b61203808">


Logo link fixed:
<img width="119" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/4a04c0c2-ef93-4ad8-992b-66dd58db93d5">

**Comment by steph-sing** [comment]
Hi Robel. All API details are still GlyGen:
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/7afc9747-7334-46b0-b732-74f5af739f1d)

Also, has the data model changed?
Previous Data Model Schema before DB edits: https://docs.google.com/drawings/d/1aAfIwEx89pw-8LYqv6BzUhuKftN49hizHu_bft29apg/edit?pli=1

**Comment by rykahsay** [comment]
Fixed, data model has not changed.

<img width="576" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/7ac955ca-637e-47d1-996d-cf0a4f6c3bb2">

**Comment by kee007ney** [comment]
@steph-sing script to pull data sets from data.argosdb.org and push them directly to HIVE 3 as .json files is finished (in this repo under the dataDumperDev branch).

Script appears to work correctly, all 15 datasets from push 1.51 are jsonized and on HIVE 3 with the name "ArgosDataSetFile."

Will you please ask someone to review these 15 datasets to make sure everything was transferred correctly (datasets are on argos@argos.org account)? If so, I will merge my branch and close this ticket.

**Comment by steph-sing** [comment]
Notes: 
Log onto [hive3.biochemistry.gwu.edu](http://hive3.biochemistry.gwu.edu/) with [argos@argos.org](mailto:argos@argos.org) and qQ123123 to look at the 15 data sets that are there now. They're named "ArgosDataSetFile" and can be seen in "All objects."
They're the json objects of the datasets from [data.argosdb.org](http://data.argosdb.org/) (for the current 1.51 release).

**Comment by steph-sing** [comment]
From what I can tell, all files are valid and I believe they contain everything in the current dataset. My only concern is the JSONs have both the BCO information and the dataset content. There is potential for this to be confusing for Nico/whomever, but not completely sure. Can the scripts be updated to just pull the dataset content per BCO ID - or maybe you could go the route of pulling the datasets by their file name? What do you think?

Again not sure if it will raise an issue but just want you to be aware. Thanks 

siteQC - ID 1266
assemblyQC - ID1267
ngsQC -  ID1272
biosampleMeta - ID 1273

Not QC but may be important for mapping:
ngs_id_list - 1271

**Comment by steph-sing** [comment]
Email will go out to Nico as an FYI tomorrow  (7/26)

**Comment by steph-sing** [comment]
Nico notified and task complete. Will create new tickets as needed.
