### ISSUE TITLE
Crandall - Update BiosampleMeta BCO to reflect use of new script

### ISSUE THREAD

**Issue by kerchner** [FDA-ARGOS/data.argosdb#226]

**Comment by kerchner** [comment]
Note to self:  I should be able to create and validate draft BCOs on the BCO server.

**Comment by kerchner** [comment]
BCO to update is. `ARGOS_000020`

**Comment by steph-sing** [comment]
@Jgergely11 and @steph-sing will review

**Comment by steph-sing** [comment]
complete
