### ISSUE TITLE
Mazumder - Update ngsQC BCO

### ISSUE THREAD

**Issue by Jgergely11** [FDA-ARGOS/data.argosdb#228]
Update BCO according to most up to date protocol

**Comment by steph-sing** [comment]
any update on this ticket?

**Comment by steph-sing** [comment]
Moving to the April Task list.

**Comment by Jgergely11** [comment]
This issue is blocked. I am having issues editing BCOs and have submitted a ticket.

**Comment by steph-sing** [comment]
will create new/better tickets for this work for all of us
