### ISSUE TITLE
Mazumder - Export BCO JSON from genome assembly workflow in HIVE

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#231]
BCO JSON is exportable on HIVE, and the following are the steps:
1. Select one or more computations from the home screen (ctrl+click for more than one). A BCO button will appear above, I then click that. In the next screen, I put my computations in the order that makes logical sense (basically how I want them to appear in the BCO ordered by objectID)
2. Then I filled out all of the details about Provenance Domain and other fields it requires, and export it (i.e. first create BCO, then download BCO JSON).

However, several things to consider: 

1. This approach is outdated and the BCO will not validate (i.e. needs manual correction);
2. When building BCO for a workflow on HIVE, there are quite some sections and fields that are no longer required in the standards on the actual BCO portal. For example, XREF. This is a discrepancy that can cause confusion and inconvenience;
3. The exported BCO does not include Extension Domain; in order words, this tool does not have any option for adding an Extension Domain, so I would need to add it manually

Please let me know the next steps, thanks.

**Comment by steph-sing** [comment]
Noted in documentation rather than an action oriented ticket. Closing for March
