### ISSUE TITLE
Mazumder - Upload multiple SARS-Cov-2 Assemblies into HIVE 3

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#234]
@penningtonea Vahan requested SARS-CoV-2 assemblies to be loaded into HIVE 3 so he can test the Genome Browser. Please upload the following assemblies to HIVE 3, share the Object IDs with Vahan in HIVE 3, and notify him via email with cc to me. Please note that none of these are reference genomes. 

Thank you

_ _ _ _ _ _ _ _ _ 
GenBank Assembly ID 
GCA_009937885.1		
GCA_009937895.1		
GCA_009937905.1		
GCA_009937915.1		
GCA_009937925.1	
GCA_009937935.1		
GCA_009937945.1		
GCA_009938055.1		
GCA_009938065.1		
GCA_009948425.1	
GCA_009948465.1		
GCA_009948495.1		
GCA_009948525.1		
GCA_009948555.1		
GCA_011536935.1		
GCA_011536975.1		
GCA_011537005.1		
GCA_011537015.1		
GCA_011537065.1		
GCA_011537075.1

**Comment by penningtonea** [comment]
Upload complete and objects shared with Vahan.
