### ISSUE TITLE
Mazumder - Biosample meta Organism names

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#236]
some Organism names appear like this: Coprococcus eutactus ATCC 27759, where 'ATCC 27759' might affect filtering

_Originally posted by @steph-sing in https://github.com/FDA-ARGOS/data.argosdb/pull/230#pullrequestreview-1316256487_

**Comment by steph-sing** [comment]
@kerchner This was another one of my review comments that was broken out into a ticket, with the intention of revisiting. I do not think this is a priority or in need of action at the moment. I think this type of discussion fits into the greater context of data standardization - as in, what should we standardize, and at what level. For me, I would consider this more data cleaning and ideally this is something our group can make time for, and I believe its important - but again - as far as priority and depth, I need clarification from the PIs.

**Comment by steph-sing** [comment]
@kerchner per the PI's comments, we won't be altering the data in anyway at this time. I will close this ticket and others in the same category. Thanks
