### ISSUE TITLE
Mazumder - Variables in Biosample meta cells are not standardized

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#237]
Variables in cells are not standardized and need to be addressed prior to release, either manually or via scripts (ideal): Not applicable vs. Not Applicable; unknown vs Unknown; Missing vs. missing 

_Originally posted by @steph-sing in https://github.com/FDA-ARGOS/data.argosdb/pull/230#pullrequestreview-1316256487_

**Comment by kerchner** [comment]
As you know, data is currently being written as retrieved from NCBI.   Do we wish to:
- Only standardize capitalization (and if so, do we choose "Loren Ipsum" or "loren ipsum")
- Use a single term across multiple variables (e.g. NA)
- Confirm that we are still using empty values where NCBI returned nothing, and that we will NOT transform any values such as "[Mm]issing" to empty values?

If there are no strong opinions on this, my inclination would be the more limited transformation, of only standardizing capitalization.  This stays as close as possible to the raw data, but mitigates the problem where Abc and abc would be treated as distinct categories in case-sensitive contexts.

**Comment by steph-sing** [comment]
thanks @kerchner for your assessment. I agree with you. Maybe there is not enough justification to standardize, and doing so would move us further away from the 'raw' data found in NCBI BioSample. How do you feel about escalating this to the group in tomorrow's collab meeting? The PIs will join and it might be nice to have their input prior to you putting in the work. thanks

**Comment by kerchner** [comment]
@steph-sing Although I can't make it to the meeting tomorrow, I've provided my input in this thread, and it would be great if this issue is discussed by the group, with any decisions documented here.

**Comment by steph-sing** [comment]
@kerchner per the PI's comments, we won't be altering the data in anyway at this time. I will close this ticket and others in the same category. Thanks
