### ISSUE TITLE
@HadleyKing @kerchner ensure dataset includes Crandall Team BiosampleMeta Data (exposed via API)

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#240]

**Comment by steph-sing** [comment]
@HadleyKing Since I absored all Crandall Datasets into our Datasets and updated the BCOs, there is no need to check for Crandall datasets from the API. You'll already get all their data from our tables once your update assemblyQc_ncbi, ngsQC_ncbi, and biosampleMeta_ncbi
