### ISSUE TITLE
Crandall - ngsQC and assemblyQC for Candida albicans and Candida parapsilosis - FDA ARGOS BioProject

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#247]
- [x] Please complete ngsQC for the following Organisms and SRRs using the HIVE ngsQC protocol. Should be a total of 24 SRR files
- [x] Please complete assemblyQC for the following fasta and genome assembly IDs. Should be a totoal of 5 genome assemblies. 
- [x] Once data is ready to be added to datasets, Check with @penningtonea for accessibility, and have @Jgergely11 review the data in each sheet. I will complete the final review. 
Thanks  

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

oranism_name | bioproject | biosample | strain | genome_assembly_id | SRR1 | SRR2 | SRR3 | SRR4 | SRR5 | SRR6
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Candida albicans | PRJNA231221 | SAMN11056371 |   | GCA_014049485.1 | SRR9073720 | SRR9073715 | SRR9073717 | SRR9073716 | SRR9073719 | SRR9073718
Candida parapsilosis | PRJNA231221 | SAMN11056368 |   | GCA_014049495.1 | SRR8984834 | SRR8984831 | SRR8984833 | SRR8984832 |   |  
Candida parapsilosis | PRJNA231221 | SAMN11056366 |   | GCA_014049455.1 | SRR8984821 | SRR8984822 | SRR8984823 | SRR8984824 | SRR8984825 | SRR8984826
Candida parapsilosis | PRJNA231221 | SAMN11056367 |   | GCA_014049445.1 | SRR8984827 | SRR8984828 | SRR8984829 | SRR8984830 |   |  
Candida parapsilosis | PRJNA231221 | SAMN11056365 |   | GCA_014049585.1 | SRR8984817 | SRR8984818 | SRR8984819 | SRR8984820 |   |  

</body>
</html>

**Comment by steph-sing** [comment]
in lieu of genome assembly ID from FDA Bio Project, please use the representative genomes and fasta per contig (8 per Org)  

c.albicans:
https://www.uniprot.org/proteomes/UP000000559 (reference proteome, with access to fasta via ENA)
https://www.ncbi.nlm.nih.gov/assembly/GCF_000182965.3/ 

c. parapsilosis
https://www.uniprot.org/proteomes/UP000005221  (reference proteome, with access to fasta via ENA)
https://www.ncbi.nlm.nih.gov/assembly/GCF_000182765.1 ( representative genome)

**Comment by penningtonea** [comment]
Downloading the RefSeq FASTA file (representative genome) into HIVE was the best troubleshooting option. No new questions from Xinyang or Emma. Will update as necessary.

**Comment by steph-sing** [comment]
perfect. thanks for the update.

**Comment by steph-sing** [comment]
Will complete as part of the April 5th data release, so I will move to April Tasks. ngsQC complete.
