### ISSUE TITLE
Use the HIVE Reference-guided genome assembly protocol to assemble sudan ebola fasta

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#249]
- [x] Use these SRR files as input into your genome assembly protocol. ngsQC data is available in our datasets (review as needed). 
 - [x] Use this as your Sudan Ebola Reference/Representative genome: https://www.ncbi.nlm.nih.gov/assembly/GCF_000855585.1/
 - [x] Attempt to look at the quality of these assemblies with your protocol prior to sending to Emily. Do you notice any quality issues? (for example, Stephen notice quality issues from this input data)
 - [x] once fasta are complete, ask Emily to QC them for you and we will review the quality of each for release to the DB (if any)
 - [ ] Propose different use cases for this data (if not genome assembly, then what?)
 - [ ] Continue to build out the reference guided genome assembly protocol 
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50761 | FDAARGOS_484 | PRJNA231221 | SAMN07796366 | SRR7167624 | SRR7167624_1.fastq
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50761 | FDAARGOS_484 | PRJNA231221 | SAMN07796366 | SRR7167624 | SRR7167624_2.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50950 | FDAARGOS_484 | PRJNA231221 | SAMN07796366 | SRR7167622 | SRR7167622_1.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50950 | FDAARGOS_484 | PRJNA231221 | SAMN07796366 | SRR7167622 | SRR7167622_2.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50984 | FDAARGOS_484 | PRJNA231221 | SAMN07796366 | SRR7167623 | SRR7167623_1.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50984 | FDAARGOS_484 | PRJNA231221 | SAMN07796366 | SRR7167623 | SRR7167623_2.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50824 | FDAARGOS_470 | PRJNA231221 | SAMN07796352 | SRR7167618 | SRR7167618_1.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50824 | FDAARGOS_470 | PRJNA231221 | SAMN07796352 | SRR7167618 | SRR7167618_2.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 51038 | FDAARGOS_470 | PRJNA231221 | SAMN07796352 | SRR7167617 | SRR7167617_1.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 51038 | FDAARGOS_470 | PRJNA231221 | SAMN07796352 | SRR7167617 | SRR7167617_2.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50959 | FDAARGOS_1167 | PRJNA231221 | SAMN16357612 | SRR17429276 | SRR17429276_1.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50959 | FDAARGOS_1167 | PRJNA231221 | SAMN16357612 | SRR17429276 | SRR17429276_2.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50974 | FDAARGOS_1167 | PRJNA231221 | SAMN16357612 | SRR17429277 | SRR17429277_1.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50974 | FDAARGOS_1167 | PRJNA231221 | SAMN16357612 | SRR17429277 | SRR17429277_2.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50998 | FDAARGOS_1167 | PRJNA231221 | SAMN16357612 | SRR17429278 | SRR17429278_1.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 50998 | FDAARGOS_1167 | PRJNA231221 | SAMN16357612 | SRR17429278 | SRR17429278_2.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 51030 | FDAARGOS_469 | PRJNA231221 | SAMN07796351 | SRR7167615 | SRR7167615_1.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 51030 | FDAARGOS_469 | PRJNA231221 | SAMN07796351 | SRR7167615 | SRR7167615_2.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 51069 | FDAARGOS_469 | PRJNA231221 | SAMN07796351 | SRR7167616 | SRR7167616_1.fastq
Sudan ebolavirus |   | Viruses; Riboviria; Orthornavirae; Negarnaviricota; Haploviricotina; Monjiviricetes; Mononegavirales; Filoviridae; Ebolavirus; Sudan ebolavirus |   | 186540 | ARGOS_000019 | v1.2 | HIVE2 | 51069 | FDAARGOS_469 | PRJNA231221 | SAMN07796351 | SRR7167616 | SRR7167616_2.fastq

</body>
</html>

**Comment by JingyueWu** [comment]
Emily and I have talked and decided to split the assemblyQC -- we each will be running half.

**Comment by steph-sing** [comment]
will be complete by COB 3/31/2023 and data will be push on April 5th.
