### ISSUE TITLE
Crandall - practice a Galaxy Assembly workflow and give feedback to Stephen Shank

### ISSUE THREAD

**Issue by kacrandall** [FDA-ARGOS/data.argosdb#253]

**Comment by penningtonea** [comment]
Recreate the assemblyQC and ngsQC workflows on Galaxy. Execute a test run using an assembly file and associated SRA data from an organism that has already been analyzed in HIVE. Prepare a brief report comparing the results across the two platforms.

**Comment by penningtonea** [comment]
Move to July task list

**Comment by steph-sing** [comment]
@penningtonea has a workflow been share with the Crandall team by Stephen?

**Comment by cwoodside1278** [comment]
This is being closed, because  we cannot finish.
