### ISSUE TITLE
Mazumder - Explore the use case of Stanford DB

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#254]
Task description: explore the use case of [Stanford University Coronavirus Antiviral & Resistance Database](https://covdb.stanford.edu/sierra/sars2/by-sequences/), and see if it can be used to detect frameshift mutations and stop codon on other organisms.

Findings: 

1. The Stanford SARS-CoV-2 DB was actually stemmed from their [HIV DB](https://hivdb.stanford.edu/hivdb/by-sequences/) and we can use it to achieve the same goal on HIV sequences. 

2. The Stanford DB cannot just be downloaded and used for other organisms. I opened their source code in my terminal and found there were thousands of different .csv files. The content of those .csv files (e.g. some contains COVID patients data, some contains gene information, etc.) confirm that this platform was built for specifically just SARS-CoV-2. It would be 3-4 months worth of work for me to do the backend development to modify and build one for other organisms and Raja thinks it is not worth it. 

Action items:

- [x] Jingyue to email Stanford DB team, asking if they have any documentation on how to deploy it (from command line is ok) for other viruses to detect frameshifts and stop codons
- [x] Once hear back, update the team.

**Comment by JingyueWu** [comment]
Here is the email reply from the Stanford team:

_Hello,

The core Sierra code can be ported to other viruses. We have created this Sudan Ebolavirus program which can be used as a template (https://github.com/hivdb/sierra-ebv). To use Sierra for another virus, the main changes that need to be done are under the `src/main` (https://github.com/hivdb/sierra-ebv/tree/main/src/main) folder.

However, we haven't provide any documentation on porting the program for other viruses. Although we does provide brief document for Sierra-HIV on how to start development environment and how to deploy the program: https://github.com/hivdb/sierra

In addition, all of our Sierra programs are open source and distributed under GPL 3.0 licence. Any kind of contributions including code improvement, unit test, documentation through GitHub pull requests are welcomed and will be appreciated.

I hope this answers your question!

Best,
Philip_

**Comment by steph-sing** [comment]
@JingyueWu Raja suggested passing this info off to @pmcneely to see if he could work with the source code you found within a couple days - if not then no biggie, but we think Pat is best suited to tell us how much work it might require for our objectives. 
- [ ] Can you please include any additional information in this ticket (objectives/deliverables) for Pat 
- [ ] Place the StanfordDB source code in this folder (https://github.com/FDA-ARGOS/data.argosdb/tree/main/lib)
- [ ] Reassign the ticket to Pat

**Comment by JingyueWu** [comment]
@pmcneely I integrated the Stanford source code in [this folder](https://github.com/FDA-ARGOS/data.argosdb/tree/main/lib), as Stephanie said in her comment above. Please locate to the folder named "covid-drdb" which is on the top. 

Thanks for purposing the potential 2 routes we could go about, I think both would be valuable and viable deployments. However, based on the group discussion during the collaborators' meeting, Sergei is going to reach out to Bob and Philip, both are his connections who are part of the database development team, to find out how feasible it is for them to deploy this for other viruses on their end. He will share updates with us once he hears back from them.

In the meantime, Stephen Shank from Pond's lab can run SNPEff on Galaxy to achieve the same objective for us. Please feel free to continue looking into it, if you have time of course, and let us know your thoughts. Thanks so much again for your time and input.

**Comment by steph-sing** [comment]
closing and archiving this ticket until we need the information again. not action items at this time.
