### ISSUE TITLE
XBB Comparative Test - COVdb and HIVE frameshift/stop codon protocol

### ISSUE THREAD

**Issue by penningtonea** [FDA-ARGOS/data.argosdb#255]
Per Raja: 
"She or someone would need to use HIVE for Marburg stop codon and frameshift evaluation. 
I think she would need to do a test run to make sure HIVE produces similar results as Stanford for xbb. Then run Marburg."

Will test this and write the protocol accordingly.

_Originally posted by @penningtonea in https://github.com/FDA-ARGOS/data.argosdb/issues/220#issuecomment-1454181173_

**Comment by penningtonea** [comment]
Preliminary testing results here: 

https://docs.google.com/document/d/1qZGK9WZZypDMcmoN23r43fRXFoxcwEQFugGZqvxPHXM/edit

**Comment by steph-sing** [comment]
not closed yet - I've reopened this and moved it to 'In Review'
