### ISSUE TITLE
Pond - Run SNPEff on selected assemblies

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#259]
Please run the following using SNPEff on Galaxy. Let me know if you need any additional information from us, thanks!

organism_name: Severe acute respiratory syndrome coronavirus 2 Wuhan-Hu-1
genome_assembly_id: GCA_009858895.3
taxonomy_id: 2697049
biosample: SAMN13922059
sra_run_id: SRR10971381

organism_name: Influenza A virus A/Puerto Rico/8/1934(H1N1)
genome_assembly_id: GCA_000865725.1
taxonomy_id: 211044
biosample: SAMEA51847918
sra_run_id: ERR2096902
This will test to see what happens when we have SRR data, but no associated genome assembly ID

organism_name: Marburg marburgvirus Musoke
genome_assembly_id: GCA_000857325.2
taxonomy_id: 11269
biosample: SAMN11077998
sra_run_id: SRR10027406

**Comment by stephenshank** [comment]
Got started on Marburg:
https://observablehq.com/@stephenshank/snp-eff-assembly-metrics

Working on porting into Galaxy for the above.

**Comment by JingyueWu** [comment]
Thanks Stephen!

Update per collaborators' meeting discussion - HIVE may have SNPEff, but we won't be treating it as a priority for April.
