### ISSUE TITLE
Mazumder - determine how long it will take to develop a deployment package for Galaxy

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#261]

**Comment by JingyueWu** [comment]
@HadleyKing Update per Raja's feedback during 4/19 collaborators meeting -- Please reach out to Stephen and do a trial for Galaxy deployment. No need to wait at this point. Please let inform him any blockers you have regarding this task.

**Comment by JingyueWu** [comment]
This task is completed upon discussing it with Hadley, Jonathon, and Pat during scrum on 6/26.
