### ISSUE TITLE
Mazumder - Identify DRM genes for Candia auris

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#267]
https://www.ncbi.nlm.nih.gov/assembly/GCA_002759435.2/

**Comment by steph-sing** [comment]
Utilize papers such as these:
https://pubmed.ncbi.nlm.nih.gov/30559369/
https://pubmed.ncbi.nlm.nih.gov/27988485/

**Comment by penningtonea** [comment]
**Step 1 of Candida auris data collection**

Check publications listed on genome page:
https://www.ncbi.nlm.nih.gov/genome/?term=txid498019[orgn]

Candida DRM table:
https://docs.google.com/spreadsheets/d/19rD65nAvbkUZTnttYWaNHtjzZV9EAIYtyxH3X4qfeCg/edit?usp=sharing

We are checking the publications that specifically mention drug resistance for gene and amino acid mutations. Note the following in the DRM table above for each publication:
- Candida strain
- wildtype amino acid
- amino acid position within the mature protein
- mutant amino acid
- name of the mature protein
- name of the gene that produces the protein
- PMID (goes in the "reference" column)
Additionally, make a _separate_ list of genes that confer resistance (ex: FUR1, ERG11) . This will be used later.

Try to read 10-13 from the genome page by Friday, 5/26 @JingyueWu

**Comment by steph-sing** [comment]
@JingyueWu please add a section in the Fungal Data Selection Protocol about how to identify DRM genes per a Candida species (Auris). This portion can be added to the end and we will clean it up later through editing.

**Comment by steph-sing** [comment]
complete. included in FDA meeting slides and DRM table for August
