### ISSUE TITLE
Crandall - ngsQC and assemblyQC for Clostridioides and Clostridium  - FDA ARGOS BioProject

### ISSUE THREAD

**Issue by Jgergely11** [FDA-ARGOS/data.argosdb#269]
- [x] Please complete ngsQC for the following organisms and all SRRs associated with each Biosample using the HIVE ngsQC protocol.
- [x] Please complete assemblyQC for the following genome assembly IDs
- [x]  Once data is ready to be added to datasets, Check with @penningtonea for accessibility, and have @Jgergely11 review the data in each sheet

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jgerg/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jgerg/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Organism | Bioproject | Biosample | Genome Assembly   ID
-- | -- | -- | --
Clostridioides   difficile | PRJNA231221 | SAMN21402692 | GCA_020341515.1
Clostridioides   difficile | PRJNA231221 | SAMN21402693 | GCA_020297525.1
Clostridioides   difficile | PRJNA231221 | SAMN21402694 | GCA_020297505.1
Clostridioides   difficile | PRJNA231221 | SAMN21402695 | GCA_020097215.1
Clostridioides   difficile | PRJNA231221 | SAMN20888886 | GCA_019931025.1
Clostridioides   difficile | PRJNA231221 | SAMN16357487 | GCA_016985475.1
Clostridioides   difficile | PRJNA231221 | SAMN11056438 | GCA_009730495.1
Clostridioides   difficile | PRJNA231221 | SAMN04875594 | GCA_002082945.2
Clostridioides   difficile | PRJNA231221 | SAMN04875595 | GCA_002082985.2
Clostridioides   difficile | PRJNA231221 | SAMN04875593 | GCA_002073735.2
Clostridium   perfringens | PRJNA231221 | SAMN13450462 | GCA_016117735.1
Clostridium   perfringens | PRJNA231221 | SAMN13450461 | GCA_016026675.1
Clostridium   perfringens | PRJNA231221 | SAMN13450435 | GCA_016026995.1
Clostridium   perfringens | PRJNA231221 | SAMN13450434 | GCA_016027155.1
Clostridium   perfringens | PRJNA231221 | SAMN13450433 | GCA_016027375.1
Clostridium   septicum | PRJNA231221 | SAMN22091648 | GCA_020736665.1
Clostridium   sp. M62/1 | PRJNA231221 | SAMN22091680 | GCA_020736365.1
Clostridium   sporogenes | PRJNA231221 | SAMN21402699 | GCA_020450145.1
Clostridium   sporogenes | PRJNA231221 | SAMN21402698 | GCA_020341555.1
Clostridium   sporogenes | PRJNA231221 | SAMN21218847 | GCA_020099295.1
Clostridium   sporogenes | PRJNA231221 | SAMN20888887 | GCA_019933215.1
Clostridium   sporogenes | PRJNA231221 | SAMN20888888 | GCA_019933195.1
Clostridium   sporogenes | PRJNA231221 | SAMN07312467 | GCA_002588205.1

</body>

</html>

**Comment by Jgergely11** [comment]
https://www.ncbi.nlm.nih.gov/sra/?term=SAMN21402692
https://www.ncbi.nlm.nih.gov/sra/?term=SAMN21402694
https://www.ncbi.nlm.nih.gov/sra/?term=SAMN13450462
https://www.ncbi.nlm.nih.gov/sra/?term=SAMN20888887

**Comment by steph-sing** [comment]
Please provide a status update

**Comment by emdelattre** [comment]
@steph-sing, I apologize for the late reply; I wanted to clarify that everything was done. Everything is done, and I have now checked off all the tasks. Thank you!
