### ISSUE TITLE
Mazumder - Prepare EQAPOL material for FDA monthly meeting in May

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#272]
Please put together EQAPOL material for Raja to review (after meeting with Duke researchers next Monday) in the next 2-3 weeks. FDA is very interested in the HIV sequence; therefore, this will be part of the content for FDA monthly meeting in May. 

Dependency is ticket #38

**Comment by steph-sing** [comment]
completed
