### ISSUE TITLE
Mazumder - Select highly pathogenic influenza (H5N7) data

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#273]
As per April FDA monthly meeting, FDA is interested in highly pathogenic influenza data. Therefore, similar to selecting H1N1 and H3N2 in ticket #245, please use [Viral_Data_Selection_Protocol_JG1_SS1](https://docs.google.com/document/d/1o0L-YIHEppWbu53qVP1yhm9neq2KQnr7/edit?usp=sharing&ouid=101713086141465545921&rtpof=true&sd=true) to select influenza H5N7 data.

**Comment by Jgergely11** [comment]
Should this be combined with #282 ?
