### ISSUE TITLE
Crandall - resume E. coli assemblyQC

### ISSUE THREAD

**Issue by penningtonea** [FDA-ARGOS/data.argosdb#274]
Perform assemblyQC for the E. coli orgs that were ngsQC'd earlier in the year.

**Comment by penningtonea** [comment]
@JingyueWu is needed to assist with this task

**Comment by steph-sing** [comment]
@penningtonea Is this task still blocked?

**Comment by emdelattre** [comment]
I have resumed, and I'm about halfway done with them all.

**Comment by steph-sing** [comment]
@emdelattre Checking in on the status of this ticket?

**Comment by emdelattre** [comment]
@steph-sing I was wrapping up and had a few left. However, with HIVE AWS having issues with uploading files and with issues with hexagon, I have been unable to finish the remaining ones. It has not been working over the last week, but Emily and others are aware of this. Hopefully, it will be up and working soon, so I can quickly wrap up the last few. Sorry about that!

**Comment by steph-sing** [comment]
All good. I will update this ticket for the HIVE team @penningtonea @kee007ney. Thanks for your patience

**Comment by emdelattre** [comment]
@steph-sing Hi, I have completed E. Coli and have added it to the assemblyqc v1.4 sheet. I just wanted to let you know before I close the ticket. Thank you for your patience!
