### ISSUE TITLE
Crandall - Improve efficiency of `biosample_complete.sh` when retrieving identical lineages more than once

### ISSUE THREAD

**Issue by kerchner** [FDA-ARGOS/data.argosdb#276]
Within a single run, we should be able to avoid duplicate requests to retrieve the same lineage.

**Comment by HadleyKing** [comment]
https://github.com/FDA-ARGOS/data.argosdb/blob/main/lib/get_linage.py

**Comment by HadleyKing** [comment]
I was thinking of modifying this so that in the [data_files](https://github.com/FDA-ARGOS/data.argosdb/tree/main/data_files) we maintained the lineage of all of the sequences we have in the DB.  So with each release we can push an updated list if we need to.

**Comment by steph-sing** [comment]
please provide an update @kerchner

**Comment by kerchner** [comment]
Closing this issue.  It is no longer needed because this script now merges lineage values from the ngsQC_HIVE metadata file (see #322).

**Comment by kerchner** [comment]
@HadleyKing Is there, separately, still a value in maintaining a list of all lineages in [data_files](https://github.com/FDA-ARGOS/data.argosdb/tree/main/data_files)?  If so, that could be a new Issue.
