### ISSUE TITLE
Crandall - Bacteria Data Selection Protocol

### ISSUE THREAD

**Issue by penningtonea** [FDA-ARGOS/data.argosdb#289]
Draft a data selection protocol for bacteria specimen. The protocol should cover how to select a reference proteome/genome organism, how to select the appropriate assemblies for your organism, and how to collect the associated raw SRA files. Please provide justification for your selections. It may be a good idea to start with Klebsiella pneumoniae  and begin data collection for this month's outbreak. I recommend starting with the fungal data selection protocol in order to find the appropriate reference organism, then move on to assembly and SRA data collection. Use the following viral and fungal data selection protocols as a reference:

**Viral data**
https://docs.google.com/document/d/1o0L-YIHEppWbu53qVP1yhm9neq2KQnr7/edit?usp=sharing&ouid=109007925777506850028&rtpof=true&sd=true

**Fungal data**
https://docs.google.com/document/d/1yTabOWyRUucxU53WhwktUG07ZmsO-6EU/edit?usp=sharing&ouid=109007925777506850028&rtpof=true&sd=true

**SRA and other data**
https://docs.google.com/document/d/1WI2-V3gNUUZYlYbBf3il60AATnHoqn73VxzUMsr8cSQ/edit?usp=sharing

**Comment by penningtonea** [comment]
Move to July task list

**Comment by steph-sing** [comment]
@kacrandall Is this something your team is able to put together?

**Comment by steph-sing** [comment]
@penningtonea Can you check if they have a google doc of this like ours? If so can you have them place it in the correct google drive folder, format it like the others, and assign me to review please? Otherwise this will be moved to YR3 - but need to know for planning purposes

**Comment by penningtonea** [comment]
@steph-sing checked in with Crandall's team, awaiting response

**Comment by penningtonea** [comment]
Link to the doc:
https://docs.google.com/document/d/1autDPahxxCMynEMFEo_Rb8WNKJl6N-xVoWyX6JX4Ml0/edit

**Comment by penningtonea** [comment]
@steph-sing Doc is in ARGOS folder Data Curation and Data Collection Documentation and ready for review

**Comment by cwoodside1278** [comment]
Download and read these documents and upload to the sharepoint. Provide a summary of what is in here and give to Raja, Hadley, Jonathon. @cwoodside1278

**Comment by cwoodside1278** [comment]
Added these documents to the ARGOS Sharepoint page under protocols.

**Comment by cwoodside1278** [comment]
I believe this is already upt ot date so I am closing it. It has been created and well tracked but maybe updating down the line
