### ISSUE TITLE
Mazumder - Complete review and update of data.argosdb datasets and BCOs + database updates

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#290]

**Comment by steph-sing** [comment]
Current BCO's being reviewed and edited: 
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Status | BCOID | File Name
-- | -- | --
Server Errors - submit to Robel | ARG_000001 | NC_045512_SARS-CoV-2_Wuhan.fasta
Needs review | ARG_000010 | reference-guided_genome_assemblies_HIVE-Hexagon.fasta
Server Errors - submit to Robel | ARG_000013 | reference-guided_genome_assemblies_Galaxy.fasta
Check Scripts + needs update | ARGOS_000009 | ngsQC_NCBI.tsv
Check Scripts + needs update | ARGOS_000010 | biosampleMeta_ncbi.tsv
Needs review | ARGOS_000011 | siteQC_HIVE.tsv
Needs review | ARGOS_000012 | assemblyQC_HIVE.tsv
Needs review | ARGOS_000014 | sars-cov-2_lineage_mutations.tsv
Check Scripts + needs update | ARGOS_000015 | property_definition.tsv
Check Scripts + needs update | ARGOS_000016 | core_property_list.tsv
Check Scripts + needs update | ARGOS_000017 | non-core_property_list.tsv
Needs Publishing | ARGOS_000018 | ngs_id_list.tsv
Needs Publishing | ARGOS_000019 | ngsQC_HIVE.tsv
In Review / Dan | ARGOS_000020 | biosampleMeta_HIVE.tsv
Needs review | ARGOS_000021 | ngsQC_PL.tsv
Check Scripts + needs update | ARGOS_000038 | assemblyQC_NCBI.tsv


</body>
</html>

**Comment by JingyueWu** [comment]
This task is completed.
