### ISSUE TITLE
Mazumder - Begin V1.0 Close Out Documentation for FDA

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#291]
- Create Close out documentation google Doc drafts in [this folder](https://drive.google.com/drive/folders/13jFJv3yk479MyYl5r6oYzZy4ytUzpE-J?usp=drive_link). 
- Create 2 volumes: Volume 1 = Technical Volume; Volume 2 = Usage Guide
- Use 0.7 margins, Arial size 11 font (standard for the Lab)
- If you wish to include color or design, please make sure things are clean. Approved project colors are: light cornflower blue 1, dark grey 4, white, or black

Please begin with the skeleton of each and reassign me this ticket to review before moving on. 
Please include the following:

**Applicable for both volumes. Some info make be duplicated such as some of the content on page 3/4:**
- [ ] Cover page including a Title of Project (FDA-ARGOS Project), Sub title (volume type and #), document version (V1.0 for both right now), Contract # (on SOW or Tech reports), and Project Period. Make sure to select appropriate headings for the entire document and be consistent. 
- [ ] 2nd page: table of contents only
- [ ] 3rd/4th page:  (headers and their content) Project Description & Project Aims (Can be taken from the FDABAA/SOW OR Tech reports (use the most recent)), Document Description (volume specific)

**Technical Volume 1:** input the following headers/sections. Adjust the phrasing/wording to make it clear and concise (as needed). If you have any suggestions please include them in your draft:

- [ ] BETSY Deployment package 
- [ ] Technical instructions for instantiation of an instance inside FDA
- [ ] Maintenance manuals  
- [ ] BioProject submission information
- [ ] GitHub manifest and access 
- [ ] API documentation
- [ ] Roles outlining responsibilities
- [ ] Chain of command for data product issues
- [ ] Appendix  

**User Guide volume 2:** 

- [ ] Data Model
- [ ] Categorization and manifest of all data products 
- [ ] Written QC usage protocols 
- [ ] Biocompute Objects Manifest
- [ ] Data.argosdb usage guide 
- [ ] Troubleshooting guide
- [ ] Help Contact
- [ ] Appendix

https://docs.google.com/document/d/1QsEYV1LzAT5mZvqc9mGIqRcfVGCL21VK-5LlmXWYJ94/edit?usp=sharing

https://docs.google.com/document/d/1CT4SG0JzN0d7-AGGS9mj9jXnh-fgLidjDgMFSLnhUg0/edit?usp=sharing

**Comment by cwoodside1278** [comment]
Created a rough skeleton for both volumes. Sent via Slack to Stephanie fo review

**Comment by cwoodside1278** [comment]
https://docs.google.com/document/d/1QsEYV1LzAT5mZvqc9mGIqRcfVGCL21VK-5LlmXWYJ94/edit?usp=sharing

**Comment by cwoodside1278** [comment]
https://docs.google.com/document/d/1CT4SG0JzN0d7-AGGS9mj9jXnh-fgLidjDgMFSLnhUg0/edit?usp=sharing

**Comment by cwoodside1278** [comment]
Added some more updates to volume 2 and some formatting

**Comment by steph-sing** [comment]
In review

**Comment by cwoodside1278** [comment]
It has begun, but with the possibility of an extension, we may not need to do this quite yet.

**Comment by cwoodside1278** [comment]
We do not need to do this, because Embleema will be in charge. Also it is extended
