### ISSUE TITLE
Mazumder - ARG_000013 and ARG_000001 BCO Errors

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#292]
Errors-I
=========
"bco_id","property_path","error","error_category"
"ARG_000013","io_domain.output_subdomain.0.uri.filename","invalid-file-name:'ObservableHQ on data 93, data 92, and others'","WARNING"
"ARG_000013","io_domain.output_subdomain.1.uri.filename","invalid-file-name:'Replace on data 210'","WARNING"
"ARG_000013","io_domain.output_subdomain.2.uri.filename","invalid-file-name:'Replace on data 209'","WARNING"
"ARG_000013","io_domain.output_subdomain.3.uri.filename","invalid-file-name:'Replace on data 208'","WARNING"
"ARG_000013","io_domain.output_subdomain.4.uri.filename","invalid-file-name:'Replace on data 207'","WARNING"
"ARG_000013","io_domain.output_subdomain.5.uri.filename","invalid-file-name:'Replace on data 206'","WARNING"
"ARG_000013","io_domain.output_subdomain.6.uri.filename","invalid-file-name:'Replace on data 205'","WARNING"
"ARG_000013","io_domain.output_subdomain.7.uri.filename","invalid-file-name:'Replace on data 204'","WARNING"
"ARG_000013","io_domain.output_subdomain.8.uri.filename","invalid-file-name:'Replace on data 203'","WARNING"
"ARG_000013","io_domain.output_subdomain.9.uri.filename","invalid-file-name:'ivar consensus on data 111 Consensus'","WARNING"
"ARG_000013","io_domain.output_subdomain.10.uri.filename","invalid-file-name:'ivar consensus on data 110 Consensus'","WARNING"
"ARG_000013","io_domain.output_subdomain.11.uri.filename","invalid-file-name:'ivar consensus on data 109 Consensus'","WARNING"
"ARG_000013","io_domain.output_subdomain.12.uri.filename","invalid-file-name:'ivar consensus on data 108 Consensus'","WARNING"
"ARG_000013","io_domain.output_subdomain.13.uri.filename","invalid-file-name:'ivar consensus on data 107 Consensus'","WARNING"
"ARG_000013","io_domain.output_subdomain.14.uri.filename","invalid-file-name:'ivar consensus on data 106 Consensus'","WARNING"
"ARG_000013","io_domain.output_subdomain.15.uri.filename","invalid-file-name:'ivar consensus on data 105 Consensus'","WARNING"
"ARG_000013","io_domain.output_subdomain.16.uri.filename","invalid-file-name:'ivar consensus on data 104 Consensus'","WARNING"
"ARG_000013","io_domain.output_subdomain.17.uri.filename","invalid-file-name:'QualiMap BamQC report on data 111'","WARNING"
"ARG_000013","io_domain.output_subdomain.18.uri.filename","invalid-file-name:'QualiMap BamQC report on data 110'","WARNING"
"ARG_000013","io_domain.output_subdomain.19.uri.filename","invalid-file-name:'QualiMap BamQC report on data 109'","WARNING"
"ARG_000013","io_domain.output_subdomain.20.uri.filename","invalid-file-name:'QualiMap BamQC report on data 108'","WARNING"
"ARG_000013","io_domain.output_subdomain.21.uri.filename","invalid-file-name:'QualiMap BamQC report on data 107'","WARNING"
"ARG_000013","io_domain.output_subdomain.22.uri.filename","invalid-file-name:'QualiMap BamQC report on data 106'","WARNING"
"ARG_000013","io_domain.output_subdomain.23.uri.filename","invalid-file-name:'QualiMap BamQC report on data 105'","WARNING"
"ARG_000013","io_domain.output_subdomain.24.uri.filename","invalid-file-name:'QualiMap BamQC report on data 104'","WARNING"
"ARG_000013","io_domain.output_subdomain.25.uri.filename","invalid-file-name:'Map with BWA-MEM on data 82, data 81, and data 102 (mapped reads in BAM format)'","WARNING"
"ARG_000013","io_domain.output_subdomain.26.uri.filename","invalid-file-name:'Map with BWA-MEM on data 78, data 77, and data 101 (mapped reads in BAM format)'","WARNING"
"ARG_000013","io_domain.output_subdomain.27.uri.filename","invalid-file-name:'Map with BWA-MEM on data 74, data 73, and data 100 (mapped reads in BAM format)'","WARNING"
"ARG_000013","io_domain.output_subdomain.28.uri.filename","invalid-file-name:'Map with BWA-MEM on data 70, data 69, and data 99 (mapped reads in BAM format)'","WARNING"
"ARG_000013","io_domain.output_subdomain.29.uri.filename","invalid-file-name:'Map with BWA-MEM on data 66, data 65, and data 98 (mapped reads in BAM format)'","WARNING"
"ARG_000013","io_domain.output_subdomain.30.uri.filename","invalid-file-name:'Map with BWA-MEM on data 62, data 61, and data 97 (mapped reads in BAM format)'","WARNING"
"ARG_000013","io_domain.output_subdomain.31.uri.filename","invalid-file-name:'Map with BWA-MEM on data 58, data 57, and data 96 (mapped reads in BAM format)'","WARNING"
"ARG_000013","io_domain.output_subdomain.32.uri.filename","invalid-file-name:'Map with BWA-MEM on data 54, data 53, and data 95 (mapped reads in BAM format)'","WARNING"
"ARG_000013","io_domain.output_subdomain.33.uri.filename","file name in BCO (reference-guided_genome_assemblies_Galaxy.fasta) does not match file name in recipes (Selected sequences from sudan-ebola-ncbi.fasta)","WARNING"
"ARG_000013","io_domain.output_subdomain.34.uri.filename","file name in BCO (reference-guided_genome_assemblies_Galaxy.fasta) does not match file name in recipes (Selected sequences from sudan-ebola-ncbi.fasta)","WARNING"
"ARG_000013","io_domain.output_subdomain.35.uri.filename","file name in BCO (reference-guided_genome_assemblies_Galaxy.fasta) does not match file name in recipes (Selected sequences from sudan-ebola-ncbi.fasta)","WARNING"
"ARG_000013","io_domain.output_subdomain.36.uri.filename","file name in BCO (reference-guided_genome_assemblies_Galaxy.fasta) does not match file name in recipes (Selected sequences from sudan-ebola-ncbi.fasta)","WARNING"
"ARG_000013","io_domain.output_subdomain.37.uri.filename","file name in BCO (reference-guided_genome_assemblies_Galaxy.fasta) does not match file name in recipes (Selected sequences from sudan-ebola-ncbi.fasta)","WARNING"
"ARG_000013","io_domain.output_subdomain.38.uri.filename","file name in BCO (reference-guided_genome_assemblies_Galaxy.fasta) does not match file name in recipes (Selected sequences from sudan-ebola-ncbi.fasta)","WARNING"
"ARG_000013","io_domain.output_subdomain.39.uri.filename","file name in BCO (reference-guided_genome_assemblies_Galaxy.fasta) does not match file name in recipes (Selected sequences from sudan-ebola-ncbi.fasta)","WARNING"
"ARG_000013","io_domain.output_subdomain.40.uri.filename","file name in BCO (reference-guided_genome_assemblies_Galaxy.fasta) does not match file name in recipes (Selected sequences from sudan-ebola-ncbi.fasta)","WARNING"
"ARG_000013","io_domain.output_subdomain.41.uri.filename","invalid-file-name:'Replace on data 49'","WARNING"
"ARG_000013","io_domain.output_subdomain.42.uri.filename","invalid-file-name:'Replace on data 48'","WARNING"
"ARG_000013","io_domain.output_subdomain.43.uri.filename","invalid-file-name:'Replace on data 47'","WARNING"
"ARG_000013","io_domain.output_subdomain.44.uri.filename","invalid-file-name:'Replace on data 46'","WARNING"
"ARG_000013","io_domain.output_subdomain.45.uri.filename","invalid-file-name:'Replace on data 45'","WARNING"
"ARG_000013","io_domain.output_subdomain.46.uri.filename","invalid-file-name:'Replace on data 44'","WARNING"
"ARG_000013","io_domain.output_subdomain.47.uri.filename","invalid-file-name:'Replace on data 43'","WARNING"
"ARG_000013","io_domain.output_subdomain.48.uri.filename","invalid-file-name:'Replace on data 42'","WARNING"
"ARG_000013","io_domain.output_subdomain.49.uri.filename","invalid-file-name:'fastp on data 40 and data 39: JSON report'","WARNING"
"ARG_000013","io_domain.output_subdomain.50.uri.filename","invalid-file-name:'fastp on data 40 and data 39: HTML report'","WARNING"
"ARG_000013","io_domain.output_subdomain.51.uri.filename","invalid-file-name:'fastp on data 38 and data 37: JSON report'","WARNING"
"ARG_000013","io_domain.output_subdomain.52.uri.filename","invalid-file-name:'fastp on data 38 and data 37: HTML report'","WARNING"
"ARG_000013","io_domain.output_subdomain.53.uri.filename","invalid-file-name:'fastp on data 36 and data 35: JSON report'","WARNING"
"ARG_000013","io_domain.output_subdomain.54.uri.filename","invalid-file-name:'fastp on data 36 and data 35: HTML report'","WARNING"
"ARG_000013","io_domain.output_subdomain.55.uri.filename","invalid-file-name:'fastp on data 34 and data 33: JSON report'","WARNING"
"ARG_000013","io_domain.output_subdomain.56.uri.filename","invalid-file-name:'fastp on data 34 and data 33: HTML report'","WARNING"
"ARG_000013","io_domain.output_subdomain.57.uri.filename","invalid-file-name:'fastp on data 32 and data 31: JSON report'","WARNING"
"ARG_000013","io_domain.output_subdomain.58.uri.filename","invalid-file-name:'fastp on data 32 and data 31: HTML report'","WARNING"
"ARG_000013","io_domain.output_subdomain.59.uri.filename","invalid-file-name:'fastp on data 30 and data 29: JSON report'","WARNING"
"ARG_000013","io_domain.output_subdomain.60.uri.filename","invalid-file-name:'fastp on data 30 and data 29: HTML report'","WARNING"
"ARG_000013","io_domain.output_subdomain.61.uri.filename","invalid-file-name:'fastp on data 28 and data 27: JSON report'","WARNING"
"ARG_000013","io_domain.output_subdomain.62.uri.filename","invalid-file-name:'fastp on data 28 and data 27: HTML report'","WARNING"
"ARG_000013","io_domain.output_subdomain.63.uri.filename","invalid-file-name:'fastp on data 26 and data 25: JSON report'","WARNING"
"ARG_000013","io_domain.output_subdomain.64.uri.filename","invalid-file-name:'fastp on data 26 and data 25: HTML report'","WARNING"
"ARG_000013","io_domain.output_subdomain.65.uri.filename","invalid-file-name:'VAPOR on data 40, data 39, and data 2: closest reference scores'","WARNING"
"ARG_000013","io_domain.output_subdomain.66.uri.filename","invalid-file-name:'VAPOR on data 38, data 37, and data 2: closest reference scores'","WARNING"
"ARG_000013","io_domain.output_subdomain.67.uri.filename","invalid-file-name:'VAPOR on data 36, data 35, and data 2: closest reference scores'","WARNING"
"ARG_000013","io_domain.output_subdomain.68.uri.filename","invalid-file-name:'VAPOR on data 34, data 33, and data 2: closest reference scores'","WARNING"
"ARG_000013","io_domain.output_subdomain.69.uri.filename","invalid-file-name:'VAPOR on data 32, data 31, and data 2: closest reference scores'","WARNING"
"ARG_000013","io_domain.output_subdomain.70.uri.filename","invalid-file-name:'VAPOR on data 30, data 29, and data 2: closest reference scores'","WARNING"
"ARG_000013","io_domain.output_subdomain.71.uri.filename","invalid-file-name:'VAPOR on data 28, data 27, and data 2: closest reference scores'","WARNING"
"ARG_000013","io_domain.output_subdomain.72.uri.filename","invalid-file-name:'VAPOR on data 26, data 25, and data 2: closest reference scores'","WARNING"
"ARG_000013","io_domain.output_subdomain.73.uri.filename","invalid-file-name:'ArgosDB SRA scrape on data 15'","WARNING"
"ARG_000013","io_domain.output_subdomain.74.uri.filename","invalid-file-name:'ArgosDB SRA scrape on data 14'","WARNING"
"ARG_000013","io_domain.output_subdomain.75.uri.filename","invalid-file-name:'ArgosDB SRA scrape on data 13'","WARNING"
"ARG_000013","io_domain.output_subdomain.76.uri.filename","invalid-file-name:'ArgosDB SRA scrape on data 12'","WARNING"
"ARG_000013","io_domain.output_subdomain.77.uri.filename","invalid-file-name:'ArgosDB SRA scrape on data 11'","WARNING"
"ARG_000013","io_domain.output_subdomain.78.uri.filename","invalid-file-name:'ArgosDB SRA scrape on data 10'","WARNING"
"ARG_000013","io_domain.output_subdomain.79.uri.filename","invalid-file-name:'ArgosDB SRA scrape on data 9'","WARNING"
"ARG_000013","io_domain.output_subdomain.80.uri.filename","invalid-file-name:'ArgosDB SRA scrape on data 8'","WARNING"
"ARG_000013","io_domain.output_subdomain.81.uri.filename","invalid-file-name:'fasterq-dump log'","WARNING"

"ARG_000001","io_domain.output_subdomain.0.uri.filename","invalid-file-name:'ObservableHQ on data 43 and data 39'","WARNING"
"ARG_000001","io_domain.output_subdomain.1.uri.filename","invalid-file-name:'Fasta Statistics on data 41: summary stats'","WARNING"
"ARG_000001","io_domain.output_subdomain.2.uri.filename","invalid-file-name:'Pluck longest on data 37'","WARNING"
"ARG_000001","io_domain.output_subdomain.3.uri.filename","invalid-file-name:'Fasta Statistics on data 37: summary stats'","WARNING"
"ARG_000001","io_domain.output_subdomain.4.uri.filename","invalid-file-name:'Assembly with MEGAHIT on data 35 and data 34'","WARNING"
"ARG_000001","io_domain.output_subdomain.5.uri.filename","invalid-file-name:'Filter SAM or BAM on data 26: bam'","WARNING"
"ARG_000001","io_domain.output_subdomain.6.uri.filename","invalid-file-name:'Map with BWA-MEM on data 23 and data 22 (mapped reads in BAM format)'","WARNING"
"ARG_000001","io_domain.output_subdomain.7.uri.filename","invalid-file-name:'fastp on data 19 and data 18: HTML report'","WARNING"
"ARG_000001","io_domain.output_subdomain.8.uri.filename","invalid-file-name:'Collapse Collection on data 16'","WARNING"
"ARG_000001","io_domain.output_subdomain.9.uri.filename","invalid-file-name:'JQ on data 14'","WARNING"
"ARG_000001","io_domain.output_subdomain.10.uri.filename","invalid-file-name:'Unique lines on data 11'","WARNING"
"ARG_000001","io_domain.output_subdomain.11.uri.filename","invalid-file-name:'Sort on data 10'","WARNING"
"ARG_000001","io_domain.output_subdomain.12.uri.filename","invalid-file-name:'Collapse Collection on data 9'","WARNING"
"ARG_000001","io_domain.output_subdomain.13.uri.filename","invalid-file-name:'JQ on data 7'","WARNING"
"ARG_000001","io_domain.output_subdomain.14.uri.filename","invalid-file-name:'fasterq-dump log'","WARNING"

**Comment by steph-sing** [comment]
@rykahsay These Warnings are the result of the BCO sanity checks. The scripts don't allow for any variability in the file name. Having more flexibility in this space is especially important for BCOs derived from Galaxy, where the intermediate steps may not result in a physical file, but its still important to note. If you have time, can you please adjust your scripts to be more flexible? If you have another approach let me know. Thanks 

Example: in ARG_000001, the first file name in the Description domain = Fasta Statistics on data 41: summary stats


![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/47393380-b876-499f-ad77-061e66f7b2ed)

**Comment by rykahsay** [comment]
It looks like this is an old one, do you still want me to do anything on this?

**Comment by rykahsay** [comment]
Allowing spaces in file names will breaks lots of things, why can't you use file names without spaces?

**Comment by steph-sing** [comment]
Hi @rykahsay completely agree that file names should not have spaces (and we implement this in all other BCOs). The issue here is content in the description domain is being scrutinized as a file name, but the content it actually describing the steps of the BCO (these are Galaxy derived so there are lots of issues). I will attempt to fix these myself, and will pull them from the DB until the issues in the BCO can be resolved.

**Comment by steph-sing** [comment]
I corrected the IO domain for both BCOs - all errors should be fixed during the next data release, V1.52


![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/1cced594-e032-444e-a3f4-7ef4ebb73ba2)
