### ISSUE TITLE
Mazumder: Re-analyze H3N2 assemblies using the approved reference genome

### ISSUE THREAD

**Issue by penningtonea** [FDA-ARGOS/data.argosdb#299]
The H3N2 assemblies in the assemblyQC table were mistakenly analyzed using the H1N1 reference genome. All of the GISAID H3N2 assemblies must be re-analyzed using reference genome assembly GCF_000865085.1

**Comment by steph-sing** [comment]
@JingyueWu @penningtonea This is Urgent. Please prioritize before the next data push on June 2nd - drop all other QC tasks until this is rectified.

**Comment by JingyueWu** [comment]
Done. https://docs.google.com/spreadsheets/d/1GyThpmDU3NyIT2dlFs7ilr13N6uuMmxU/edit?usp=sharing&ouid=112104108364280622172&rtpof=true&sd=true

**Comment by JingyueWu** [comment]
Closing this ticket as all tables have been reviewed and that V1.49 push is happening today.

**Comment by JingyueWu** [comment]
Closing this ticket as all tables have been reviewed and that V1.49 push is happening today.
