### ISSUE TITLE
Reference organisms and BCOs for their proteomes, genomes

### ISSUE THREAD

**Issue by rajamazumder** [FDA-ARGOS/data.argosdb#3]
These are the reference proteomes and their genomes we are bringing into data.argosdb.org for HIV, Salmonella, Marburg, SARS-CoV-2, Influenza A.  We will add more references under this node within the next 3 months based on input from Sergei and Keith. I just wanted to get started. So in a week if you go to beta-data.argosdb.org you will find downloads for these with a README in form of a BCO where you can see why they were chosen. We can always replace them with something else if there is a better option.

I used https://proteininformationresource.org/rps/data/current/75/rpg-75.txt to find the reference Salmonella from the largest group and we can bring in representatives from the smaller groups also into argos later to show any assembled genomes in a phylogenetic tree with them. For viruses we are using https://proteininformationresource.org/rps/viruses/data/current/95/rpg-95.txt . The proteome clusters are updated every couple of months by PIR and UniProt. For algorithm see https://pubmed.ncbi.nlm.nih.gov/27153712/ and https://pubmed.ncbi.nlm.nih.gov/21556138/.

- UP000002241	11706	HV1H2	Human immunodeficiency virus type 1 group M subtype B (isolate HXB2) (HIV-1)
-  UP000001014 Salmonella typhimurium (strain LT2 / SGSC1412 / ATCC 700720) also known as Salmonella enterica subsp. enterica serovar typhimurium strain LT2. 
- UP000464024 2697049	 SARS2	Severe acute respiratory syndrome coronavirus 2 (2019-nCoV) (SARS-CoV-2)
- UP000180448	33727	MABVM	Lake Victoria marburgvirus (strain Musoke-80) (MARV)
- UP000009255	211044	I34A1	Influenza A virus (strain A/Puerto Rico/8/1934 H1N1)

I have intentionally left out HCV for now.

**Comment by rajamazumder** [comment]
For SARS we need to do this one also https://www.fda.gov/medical-devices/database-reference-grade-microbial-sequences-fda-argos/fda-argos-sars-cov-2-reference-grade-sequence-data

**Comment by rajamazumder** [comment]
Flu reference NGS file email to Joe, Pond team etc- can you please show James how to do QC on HIVE? He can start with Influenza A example. I am cc-ing Sergei to let them know what we are trying out. If they are also doing anything similar with Flu A then we can compare results. Ccing Robert as he mentioned Flu A should be there in Feb release. 
Influenza A virus (A/Puerto Rico/8/1934(H1N1)) NGS data: https://www.ncbi.nlm.nih.gov/sra/ERX2154267[accn]
README/BCO text that James will need: List of SRA IDs were retrieved using search string in SRA "txid211044[Organism:exp] ". The SRA ID was selected based on NCBI search filters Source: RNA, Type: genome, Library layout: paired, Platform: Illumina. 
File is in cram format and needs to be changed to bam or fastq to use in HIVE.
This project might help us get additional NGS files that ARGOS can use. "This project aims to sequence the genomes of RNA viruses in the National Collection of The NCPV preserves well-characterised, authenticated human pathogenic viruses in a secure facility, and supplies the agents or nucleic acids derived from them to the scientific community. The genomes sequenced within this project will be a valuable additional resource that will also be made available to the scientific community."

**Comment by steph-sing** [comment]
Complete - Closed
