### ISSUE TITLE
All Teams - June FDA meeting slides

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#300]
https://docs.google.com/presentation/d/1cvTGNieYeXhmsj3pc7XsZzujsaIT_lPVWu5Ud7sZFlo/edit?usp=sharing
Items for June FDA meeting June 14th:

- [x] 1 slide - general data team updates @steph-sing 
- [x] 1 slide - data.argosdb.org updates (connected to ticket #208) @steph-sing 
- [x] 1 slide - present updates to the V1.4 Data Dictionary; Annotation dictionary @steph-sing 
- [x] 2-4 slides - DRM pipeline on influenza and/or Candida sp. (with figure); new DRM tables released to the DB @penningtonea @JingyueWu 
- [x] 1-2 slides - Galaxy annotation workflows (connected to ticket #287) @stephenshank 
- [x] 1-2 slides - BETSY deployment update (containerization complete? Betsy Demo and not local) @kee007ney @pmcneely  
- [x] 1 slide - Galaxy containerization status @HadleyKing 
- [x] 1 slide - June/July planning @steph-sing

**Comment by JingyueWu** [comment]
This task is completed, closing this ticket.

**Comment by steph-sing** [comment]
@JingyueWu I don't see where this was completed? There are not any slides in the draft slides. Can you please put all draft materials in the correct space and reassign me when that is done? 
We will still complete this draft content even though the July meeting will be absorbed into the August 2023 meeting.

**Comment by steph-sing** [comment]
complete
