### ISSUE TITLE
Implement dynamic display of filter numbers

### ISSUE THREAD

**Issue by jeet-vora** [FDA-ARGOS/data.argosdb#302]
- [ ] When selecting filters in the side bar, the numbers reflected in each category do not adjust to the currently available selection based on the current filters being applied 
Example: after selecting Datasets Body, searching 'Kinase' in the search bar, and selecting Homo sapiens in the filters (which shows a list of 48 files), other #'s next to the filtering options did not adjust to the current search criteria. For example,  the # of CSVs or Reviewed datasets remains the same and out numbers the list of 48 files 
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/48079325-3170-408c-8292-8d3209d06b83)

![image](https://github.com/FDA-ARGOS/data.argosdb/assets/25825266/80d5bd76-b8c9-4052-b275-5ef926321866)

**_Action Item - Implement dynamic display of filter numbers. Proposed way is the portal should talk to the server and provide the filter number.  Certain options that do not yield any search results because of and operation instead of or (mouse and human kinase). Also add Remove All / Reset Filters option_** 
@steph-sing

**Comment by JingyueWu** [comment]
@rykahsay Can you please provide me with the update for this ticket and the estimated time to address it?

**Comment by rykahsay** [comment]
Check beta now:
<img width="1388" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/aad0a4c1-6539-4768-a647-5807ac4b89bd">

**Comment by steph-sing** [comment]
Complete. Closing ticket
