### ISSUE TITLE
Allow the search bar to search BCO name with special character ( )._

### ISSUE THREAD

**Issue by jeet-vora** [FDA-ARGOS/data.argosdb#303]
- [ ] search bar does return results for a specific BCO name Dataset Metadata (any bco name with special characters like () searches do not work) Also the search is not very powerful as it does not search partial word like Ortho entire word has to be searched Ortholog.
Example: BCO name: Human O-GlcNAc Glycosylation Citations (O-GlcNAc Atlas); File Name:human_proteoform_citations_glycosylation_sites_oglcnac_atlas.csv 
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/c5d82a53-7391-4542-9ae8-406282ae29b1)
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/6418279e-3d87-4855-95f3-b973fa59bd55)
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/63a7558a-4124-4c9d-bab2-8eb44dee9085)

**_Action Item - Allow the search bar to search BCO name with special character._**
@steph-sing

**Comment by JingyueWu** [comment]
@rykahsay Can you please provide me with the update for this ticket and the estimated time to address it?

**Comment by steph-sing** [comment]
complete. closing ticket
