### ISSUE TITLE
Mazumder - Implement a search caching for showing searched results when back button is clicked

### ISSUE THREAD

**Issue by jeet-vora** [FDA-ARGOS/data.argosdb#304]
- [ ] No option to return to a previous page when back button is pressed, the page resets and does not show the search entered.:
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/6e74f52a-d6eb-4fe6-8963-b25ee11f9ce9)

**_Action Item - Implement a search caching for showing searched results when back button is clicked._**
@steph-sing

**Comment by HadleyKing** [comment]
I have not fully implemented it yet but for the BCO Portal I have a state object that is reserved to save a list of searches (the request json sent to server) and a list of results in the browser. This may be less of a lift to implement and will put the data in the browser so the server will not have to manage the data.

**Comment by JingyueWu** [comment]
@rykahsay Based on Hadley's comment above, can you please provide me with the update for this ticket and the estimated time to address it?

**Comment by rykahsay** [comment]
Done --> check on beta

**Comment by rykahsay** [comment]
<img width="767" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/38003798-dbe6-472e-a73a-77f24302f062">

**Comment by steph-sing** [comment]
complete thank you @rykahsay
