### ISSUE TITLE
Rows per page Option 200 does not work

### ISSUE THREAD

**Issue by jeet-vora** [FDA-ARGOS/data.argosdb#305]
- [ ] Rows per page option 200 at the bottom of the page does not work. 
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/25825266/a214f251-a153-4824-8fe4-939e4164b36a)

**_Action Item - Ensure Rows per page option 200 is working where applicable._**

@steph-sing

**Comment by JingyueWu** [comment]
@rykahsay Can you please provide me with the update for this ticket and the estimated time to address it?

**Comment by rykahsay** [comment]
The library I am using does not allow me to go more than 100, so I have fixed it as shown

<img width="1362" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/277dc632-c581-4b1e-ac28-877d29a83b3c">

**Comment by steph-sing** [comment]
reflected in ARGOS. closing ticket
