### ISSUE TITLE
Highlight the BCO JSON tab when searched under dataset metadata

### ISSUE THREAD

**Issue by jeet-vora** [FDA-ARGOS/data.argosdb#306]
- [ ] Just like when you search a specific term under **dataset body** the details page of the selected dataset shows matched records however the same is not true when a specific term is searched under **dataset metadata**, the selected dataset does not show where the term appears in the BCO JSON or readme. When the dataset is selected, it should show the BCO JSON or Readme tab and highlight the text that matched the search.

The below image show matched records for kinase when kinase is searched under dataset body.
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/25825266/111c691b-85e6-4568-a3f6-c16bb9c06b5e)

**_Action Item - Highlight the BCO JSON tab when searched under dataset metadata_**

@steph-sing

**Comment by JingyueWu** [comment]
@rykahsay Can you please provide me with the update for this ticket and the estimated time to address it?

**Comment by steph-sing** [comment]
Due to functionality hinderance, I will close this ticket.
