### ISSUE TITLE
Search Types

### ISSUE THREAD

**Issue by jeet-vora** [FDA-ARGOS/data.argosdb#307]
- [ ] Rather than calling "dataset body" it should be called "dataset entries" or "dataset content"
**_Action Item - 
Option 1 Have three search type 1) All or data_metadata 2) dataset_metadata 3) dataset_entries 
Option 2 Have two searches 1) All or data_metadata 2) dataset_entries
For all* the result page showed show both links for BCO Json and matched records for the dataset for users to select_**
@steph-sing

**Comment by JingyueWu** [comment]
@rykahsay Can you please provide me with the update for this ticket and the estimated time to address it?

**Comment by rykahsay** [comment]
We have agreed to search everything all the time:
<img width="838" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/8ddc75e5-f4d9-4e25-abbe-aea6b85567f9">
