### ISSUE TITLE
Mazumder - v1.4 Data dictionary to GitHub

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#308]
- [x] Commit V1.4 Data Dictionary to GitHub space
- [x] run V1.4 Error Testing

Excel Link: https://docs.google.com/spreadsheets/d/1t5kgTxalcDS7sUfpqv7Ila_wV9acv2sF4571w_Mm0_A/edit?usp=sharing

**Comment by steph-sing** [comment]
@HadleyKing do you have an update for this ticket? I saw you updated the google drive but don't see updated in GitHub? Let me know if you want to pass this off to me

**Comment by HadleyKing** [comment]
https://github.com/FDA-ARGOS/data.argosdb/pull/325
