### ISSUE TITLE
Mazumder - Draft DRM protocol

### ISSUE THREAD

**Issue by penningtonea** [FDA-ARGOS/data.argosdb#316]
- [x] Draft DRM protocol from the current HIVE workflow 
- [x] update the DRM BCO to reflect the protocol steps
- [ ] Publish the DRM protocol and share with data teams

**Comment by penningtonea** [comment]
Move to July task list

**Comment by steph-sing** [comment]
@penningtonea Please provide a status update

**Comment by penningtonea** [comment]
Protocol draft is ready for revision. The draft is available in the ARGOS living drafts folder here: 
https://docs.google.com/document/d/18PziUgFKhkH4f8wJNCrkmYEUSYGf_BnH_xwZvpDO4T0/edit#heading=h.gjdgxs

**Comment by steph-sing** [comment]
complete
