### ISSUE TITLE
Mazumder - update assemblyQC BCO

### ISSUE THREAD

**Issue by penningtonea** [FDA-ARGOS/data.argosdb#317]
Update the assemblyQC protocol to include all of the steps in the current version.

**Comment by penningtonea** [comment]
@steph-sing @HadleyKing draft has been updated and is ready for review.

**Comment by steph-sing** [comment]
@HadleyKing @penningtonea I am getting errors and seeing a blank draft for this BCO. Can you look into this?


![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/f1368f46-1c7b-459c-8ba8-030be2cfc483)

**Comment by steph-sing** [comment]
@penningtonea Did you finish editing and updating after we had our meeting a few weeks ago?

**Comment by penningtonea** [comment]
Yes, closing the ticket now.
