### ISSUE TITLE
All teams - July FDA meeting slides

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#319]
https://docs.google.com/presentation/d/1cvTGNieYeXhmsj3pc7XsZzujsaIT_lPVWu5Ud7sZFlo/edit#slide=id.g251f62021d3_3_0

- [x] 1~3 slides at least one analysis table (influenza) from DRM pipeline + a draft of DRM pipeline @penningtonea 
- [x] 1 slide on data updates + 1 slide on updates to annotation data dictionary (maybe V1.5) @steph-sing 
- [x] 1 slide on QC paper @steph-sing 
- [x] 1~2 slides on BETSY updates @kee007ney @pmcneely 
- [x] 1~2 slides on Galaxy instances for FDA @HadleyKing @stephenshank 
- [x] @JingyueWu check in with Raja about content the last week of June

**Comment by JingyueWu** [comment]
Meeting update with @stephenshank : rather than showing the full Galaxy instances for FDA in July, it would be more feasible to show the updates on assemblyQC pipeline (focus on GenBank part) OR another tool on their instance. 

The whole Galaxy instance for FDA including 4 core tables would most likely be available in September.

**Comment by steph-sing** [comment]
I would still like the draft content to be added to the slides by 7/7. we need this material for the Tech report
