### ISSUE TITLE
Application deployment for ARGOS

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#320]
Per meeting with Raja and Robel -- Jingyue deploys application to ARGOS test server ([test.argosdb.org](http://test.argosdb.org/)).. Wait until GlyGen 2.1 gets pushed on Friday (6/30). This will be next week's focus. Must be completed 2 weeks from today (deploy on Friday from this Friday). 

See instructions: https://github.com/glygener/glygen-backend-datasetviewer 

Reach out to Tianyi for guidance and help. 

Once completed, update steps for ARGOS documentation.

**Comment by JingyueWu** [comment]
As of June 27 evening, request to access the ARGOS test server has been made to Dacian.

**Comment by rykahsay** [comment]
Deployment done on:
- https://data.test.argosdb.org/
- https://beta-data.argosdb.org/
- https://data.argosdb.org/

Data release 1.51 was created using the same old pipeline on dev server.

**Comment by steph-sing** [comment]
I will set up testing on a separate ticket. 
@rykahsay Let me know if you'd like us to report errors under this ticket, or close this ticket and open new tickets as needed. Thanks

**Comment by steph-sing** [comment]
Completed by Robel
