### ISSUE TITLE
BETSY deployment 

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#321]
Creating this new ticket to follow up. In addition, per Raja's comment during Monday's scrum -- for Jonathon and Pat, if this is not done by 7/14, please schedule a call with Raja.

**Comment by kee007ney** [comment]
The next iteration was completed on Wednesday 7.12.2023, but did not solve the throttling issue. We essentially deployed entirely to RAM this time, but are still seeing very slow page load times.

So we've eliminated some configuration possibilities, but now have no idea what the source of the throttling is. We will regroup and plan something else to troubleshoot.

**Comment by steph-sing** [comment]
Based on conversations with Raja, Jonathon, and Pat I am considering this ticket closed. I will make new tickets as needed for the BETSY work (most likely in GW Prod)
