### ISSUE TITLE
Mazumder - Remaining BCO edits and review

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#328]
Several BCOs still need to be reviewed, edited, versioned, and published to address errors in the DB. A record of these BCOs can be found here (please make sure to use the V1.50 tab for current BCO edits: [All BCO Edits](https://docs.google.com/spreadsheets/d/1uA21djJrp0Y8ZQdzlpqsWmWrCn-8EAzaL5JAUatKjMY/edit?usp=sharing)

- [x] Check-in timeline will be July 14th

- [x] The BCOs that have remaining errors are listed here. The errors here are not exhaustive, so please note that the entire BCO will need to be reviewed on a detailed level. For example, ensure that the authors and their contributions (including their ORCIDs are included and correct; check the usability domains if description domains have been updated, check all URIs etc.)

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Status | BCOID | File Name
-- | -- | --
Error in Description Domain an Execution Domain - BCO | ARGOS_000010 | biosampleMeta_NCBI.tsv
Update by Dan | ARGOS_000020 | biosampleMeta_HIVE.tsv
Errors in Description Domain; needs to update tag in Exc Dom | ARGOS_000038 | assemblyQC_NCBI.tsv

</body>
</html>

- [x] Work with Dan, Hadley, or consult written protocols as needed to ensure the BCOs are up to date.

- [x] Need to ensure correct scripts are logged in order for certain BCOs, and the URIs are correct (should be the GitHub Lib space at the very least). 

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

assemblyQC_NCBI.tsv | Notes | Scripts in Order for BCO
-- | -- | --
  | - manifest of the scripts per a table |  
  | - need to know how to apply the scripts in the correct order | https://github.com/FDA-ARGOS/data.argosdb/blob/main/lib/efetch_bioproject_runs.sh
  | - Update README: Describes steps and scripts being used | https://github.com/FDA-ARGOS/data.argosdb/blob/main/lib/xml_feature_parser.py
  |   | https://github.com/FDA-ARGOS/data.argosdb/blob/main/lib/eutils_SRAcurl_experiments.sh
  |   | https://github.com/FDA-ARGOS/data.argosdb/blob/main/lib/assembly_qc_ncbi_.py
ngsQC_NCBI.tsv | Notes | Scripts in Order for BCO
  |   | https://github.com/FDA-ARGOS/data.argosdb/blob/main/lib/xml_feature_parser.py
  |   | https://github.com/FDA-ARGOS/data.argosdb/blob/main/lib/shell/eutils_SRAfetch_experiments.sh
  |   | https://github.com/FDA-ARGOS/data.argosdb/blob/main/lib/sra_run_parser.py
  |   | ?
  |   |  
  |   |  
biosampleMeta_NCBI.tsv | Notes | Scripts in Order for BCO
  |   | https://github.com/FDA-ARGOS/data.argosdb/blob/main/lib/shell/efetch_bioproject_biosample.sh
  |   | ?

</body>
</html>

Please let me know if you have any questions.

**Comment by Jgergely11** [comment]
- Issues with ARGOS_000010 and ARGOS_000038 have been resolved and BCOs are valid. ARGOS_000020 will still need more time. 
- ARGOS_000009, ARGOS_000010, and ARGOS_000038 have been updated with proper ORCIDs
- Scripts have been updated and verified
- Description Domains flow more intuitively

**Comment by steph-sing** [comment]
ARG_000001 and ARG_000013 errors have been addressed as well.
@Jgergely11 is Finalizing edits for ARGOS_000010 and ARGOS_000020

**Comment by Jgergely11** [comment]
@steph-sing  Edits are completed

**Comment by steph-sing** [comment]
all complete
