### ISSUE TITLE
Mazumder - Fixing data.argosdb.org banner issue

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#330]
Scroll to the bottom of https://data.argosdb.org -- the bottom banner is still GlyGen. Please fix this: 

<img width="629" alt="Screen Shot 2023-07-19 at 3 30 29 PM" src="https://github.com/FDA-ARGOS/data.argosdb/assets/61590108/9e8f50d4-471d-4a28-9018-eec51fda6791">

**Comment by JingyueWu** [comment]
@rykahsay This is an urgent action item, any update?

**Comment by steph-sing** [comment]
@rykahsay Please add CC BY 4.0 to the banner

**Comment by rykahsay** [comment]
I have added "CC BY 4.0" to the footer but I am not sure if that is exactly what you wanted -- check https://data.test.argosdb.org/
