### ISSUE TITLE
Mazumder - Fix file name for ARG_000001 and ARG_000013

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#331]
Currently on https://data.argosdb.org, we have these as file names for the two BCOs:

<img width="633" alt="Screen Shot 2023-07-19 at 3 35 45 PM" src="https://github.com/FDA-ARGOS/data.argosdb/assets/61590108/12e3aa37-985b-416b-a135-6b981ad8b1c6">

Please refer to their correct corresponding file names on [All_BCO_Edits](https://docs.google.com/spreadsheets/d/1uA21djJrp0Y8ZQdzlpqsWmWrCn-8EAzaL5JAUatKjMY/edit?usp=sharing) (see v1.49 tab) and edit file names in the IO Domain.

**Comment by Jgergely11** [comment]
I do not have the required permissions to edit these BCOs

**Comment by Jgergely11** [comment]
Re-assigning to @HadleyKing . The filename needs to be updated in the I/O domain

**Comment by steph-sing** [comment]
I resolved this issue by updating the BCO. Will see results after the next data release.
