### ISSUE TITLE
Mazumder - Propose a new FAQ page with more questions in the next week or two

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#332]
Current FAQ page only has 5 questions: https://data.argosdb.org/static/faq

Jingyue (primary) and Emily (and later other team members) propose a new FAQ page with more questions in the next week of two.

**Comment by JingyueWu** [comment]
Status update per Raja's feedback: Remove questions regarding license, copyright, and data distribution. Incorporate these information in the banner. Jonathon, Pat, and Raja are double checking MIT license. Jingyue continues working with Stephanie to finalize the responses. 

This needs to be done before the data push next Friday (8/4)

**Comment by JingyueWu** [comment]
Modify FAQs with @steph-sing  on Friday: https://docs.google.com/document/d/1vQo8GeIBC7XuV-P4mtGYLsOI9pDptPmoSEjx5SZnJdU/edit?usp=sharing 

Once done, this will be included in the data release next week.

**Comment by steph-sing** [comment]
FAQs will be updated as part of v1.54
