### ISSUE TITLE
Mazumder - Add connection to APIs in the data.argosdb.org tabs

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#333]
Just like GlyGen has a tab designated for APIs (right image in the screenshot), please also implement APIs on https://data.argosdb.org

<img width="1439" alt="Screen Shot 2023-07-19 at 3 44 50 PM" src="https://github.com/FDA-ARGOS/data.argosdb/assets/61590108/fd1de3ae-8cb5-4db6-a6a5-99ca918db66d">

FYI @steph-sing

**Comment by JingyueWu** [comment]
@rykahsay This is an urgent action item -- any update?

**Comment by steph-sing** [comment]
Complete. Thank you @rykahsay
