### ISSUE TITLE
Mazumder - Fixing fav_icon for data.argosdb.org

### ISSUE THREAD

**Issue by JingyueWu** [FDA-ARGOS/data.argosdb#334]
The fav_icon still shows GlyGen's on the tab:

<img width="870" alt="Screen Shot 2023-07-25 at 10 58 06 AM" src="https://github.com/FDA-ARGOS/data.argosdb/assets/61590108/892d4fa1-361a-41a5-8679-8fb9a64ad17f">

Please fix this asap

**Comment by rykahsay** [comment]
<img width="296" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/9ea166bc-749f-42dd-bc7d-deee20a04b5d">

**Comment by steph-sing** [comment]
@rykahsay it is still appearing in the tab.


![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/98f9c795-9291-41a4-946b-a0dc5f5e8a06)

**Comment by JingyueWu** [comment]
For me, I found that the GlyGen fav icon appears in Safari browser. But on chrome, firefox, and microsoft edge it's the argos icon

**Comment by steph-sing** [comment]
Interesting, I see it still in Chrome

**Comment by steph-sing** [comment]
I see it is fixed. Will close this ticket
