### ISSUE TITLE
Mazumder - ARGOS APIs still reflecting GlyGen content

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#335]
ARGOS APIs still contain GlyGen information. Example: Glyca Finder 

![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/5cb34db3-d8af-4d70-997a-034ef87d0b7f)

**Comment by rykahsay** [comment]
<img width="626" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/79dc3b05-c6b0-444d-9aeb-cce349a02bde">

**Comment by steph-sing** [comment]
complete
