### ISSUE TITLE
Mazumder - Add connection to the Front End site to the data.argosdb tabs

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#336]
Just as in GlyGen, please add a tab for the ArgosDB Front End to the tabs in data.argosDB

![Image](https://user-images.githubusercontent.com/70154794/255976629-b4ad7dcc-a2b9-4148-a614-2576744b0778.png)

![Image](https://user-images.githubusercontent.com/70154794/255976675-c39e5758-96c4-4853-84bb-9944a338b8b2.png)

ARGOS Portal: https://argosdb.org/

![Image](https://user-images.githubusercontent.com/70154794/255976897-cb2a3b5d-23ae-4a36-b895-cc51afd56d1f.png)

**Comment by rykahsay** [comment]
<img width="633" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/9aad8483-a1ac-4fee-923d-d1c0dd18aacb">

**Comment by steph-sing** [comment]
Thanks @rykahsay 
It seems the PORTAL Tab redirects right back to the home pages of data.argosdb.org, but I need it to point, here: ARGOS Portal: https://argosdb.org/
