### ISSUE TITLE
Phase 1 DB Updates: Font of the headers is too small

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#340]
please increase the font size of the ARGOS Headers

![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/d1689715-a1f1-4fd2-85da-2afad5481970)

**Comment by rykahsay** [comment]
Fixed

**Comment by steph-sing** [comment]
@rykahsay Looks great, but I don't see your previous changes of adding 'Portal' and 'API' to the header tabs in Test?

**Comment by rykahsay** [comment]
Check now

**Comment by steph-sing** [comment]
great, complete
