### ISSUE TITLE
Phase 1 DB Updates: Icon logos in the banner are too large

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#341]
These images are every large. Please make them smaller, centered in the page/banner, and include the CC BY 4.0 in the banner (also outlined in ticket #330)

![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/53b9e5c1-345c-4f85-a883-095f5dfe3f17)

**Comment by rykahsay** [comment]
"... and include the CC BY 4.0 in the banner"

What exactly should be the CC message??

**Comment by steph-sing** [comment]
Hi Robel, please include this language centered in the banner:

Funded by the Food and Drug Administration contract # 75F40121C00167

We have chosen to apply the [Creative Commons Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/) license to all our database sets. This means that you are free to copy, distribute, display and make commercial use of these databases in all legislations, provided you give us credit.

**Comment by rykahsay** [comment]
<img width="1300" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/c1329f72-57df-4961-a26b-26f982415e52">

**Comment by steph-sing** [comment]
perfect - thank you
