### ISSUE TITLE
Phase 1 DB Updates: Add function to 'Matched Records'

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#342]
Should be able to download the 'matched records' return from a specific search as a dataset that includes the headers of the main dataset. Example: Salmonella input into Search bar, selecting ngsQC (returned 87 salmonella-specific rows in 'matched records' --> should be able to download this specific set of data rather than the entire dataset

![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/f276d3a6-efcc-441f-8c19-07e9a256b3c7)

**Comment by rykahsay** [comment]
Done -- go to DOWNLOADS tab

<img width="1043" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/0bdd99d7-6bee-4d4f-8d02-9a82ca3420a7">

**Comment by steph-sing** [comment]
Thanks @rykahsay - it downloads as a txt file. Is there anyway to make it download as a TSV?

**Comment by steph-sing** [comment]
@rykahsay  it downloads as a txt file. Is there anyway to make it download as a TSV?

**Comment by rykahsay** [comment]
Please check on prd, it downloads tsv file

**Comment by steph-sing** [comment]
yes it works. Complete
