### ISSUE TITLE
Mazumder - DB Edits: Fixing letter casing in filters

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#345]
Certain font casing is intentional for Argos datasets and it's important to keep them consistent. Please allow the casing outlined in the BCO extension domains to be reflected in the DB filters. 

Here's a list of items to change in the DB:

By Priority: 
- [ ] 'Core, annotation' --> should read 'Core, Annotation' 

![Image](https://user-images.githubusercontent.com/70154794/258893422-6b5bdedb-3199-46dd-9582-fca70a2a1f2b.png)

By Tag:
- [ ] 'Assemblyqc' --> should read 'assemblyQC' 
- [ ] Ngsqc --. should read 'ngsQC'
- [ ] Siteqc --> should read 'siteQC'
- [ ] biosamplemeta --> should read 'biosampleMeta'
- [ ] Organism tracking, ngsqc --> should read 'Organism tracking, ngsQC' 

![Image](https://user-images.githubusercontent.com/70154794/258894488-6db890d1-d268-4654-b26f-bc9a4a17cc7b.png)

Additional Example:
How ARGOS_000019 font casing is presented in the BCO:

![Image](https://user-images.githubusercontent.com/70154794/258892062-d3086aad-f227-479d-9704-1f24776868e9.png)

How ARGOS_000019 filter shows up on the website:

![Image](https://user-images.githubusercontent.com/70154794/258892979-c5ca08bd-17d6-405d-9262-dad4d4cfae83.png)

**Comment by rykahsay** [comment]
I have stopped changing the first letter to upper case but the rest should be under your control. Let's wait until you make another data push

**Comment by steph-sing** [comment]
Okay thank you - I will test this and make edits as needed. I'll close this ticket once testing is complete
