### ISSUE TITLE
Mazumder: Phase 2 DB updates: Option to download the full BCO as a JSON OR link out to the BioCompute Object directly

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#346]
Option to download the full BCO as a JSON OR link out to the BioCompute Object directly, or both  

On this page: 

![Image](https://user-images.githubusercontent.com/70154794/258900018-a61647c3-4233-44b6-a7bb-6f91c9b88a3d.png)

**Comment by rykahsay** [comment]
It can be downloaded from the "DOWNLOADS" tab now

<img width="954" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/71799685-dcd9-4b81-a012-fb0af5bfeebc">

**Comment by steph-sing** [comment]
complete
