### ISSUE TITLE
Mazumder - Data release error: Unable to push V1.52 to Production

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#350]
During the data release V1.52 to Production, When running: python3 object-maker/make-historydb-pairs.py -v $ver where ver=1.52 - this error returns: 

![Image](https://user-images.githubusercontent.com/70154794/259227094-5d4a86ca-3d7f-4892-8efe-18ca9a7e30b1.png)

if we understand correctly, it appears to be referencing this:
https://api.argosdb.org/misc/verlist
That value is quoted, so it could be the source of the problem, but we don't know where that value comes from (last DB data release version?)

Clear sanity checks for:

- datasets clear of errors
- python3 dataset-maker/check-recipe-sanity.py 
- python3 dataset-maker/check-bco-sanity.py

@rykahsay Can you please assist?

**Comment by steph-sing** [comment]
@kee007ney @HadleyKing

**Comment by steph-sing** [comment]
@rykahsay Also the Release History is not showing up in Production:


![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/14b7ce91-92ab-43e1-a8c5-1a390213239b)

**Comment by rykahsay** [comment]
I have fixed the issue with object-maker/make-historydb-pairs.py  and object-maker/make-historydb-tracks.py, and also run those steps for 1.52.

Now the history_list pages looks as shown below:

<img width="854" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/b4c69ea6-5a6b-4238-9c17-9c437e40aea2">

**Comment by steph-sing** [comment]
complete
