### ISSUE TITLE
Mazumder - README update for data.argosDB Repo

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#357]
v1.5 branch should have an up-to-date README per the paper

**Comment by cwoodside1278** [comment]
Needs to be done immediately. Updated multiple times up until paper is printed.

**Comment by cwoodside1278** [comment]
Generic enough, but looks good. Link to other places.

**Comment by cwoodside1278** [comment]
Will update once the v1.6 schema has been uploaded and updated.

**Comment by cwoodside1278** [comment]
Realizing this is a duplicate. Closing because there is another task on this specifically for v1.6
