### ISSUE TITLE
Mazumder - Strange authentication error blocking v1.53 data release

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#359]
@rykahsay While calling file: deploy-data.sh - error below occurred. Can you assist?  

![Image](https://user-images.githubusercontent.com/70154794/262147216-f5594970-e33c-4c58-b770-88346f0a91fb.png)

**Comment by rykahsay** [comment]
mongodb was down -- please try now

**Comment by steph-sing** [comment]
@rykahsay Still getting a certificate error from Jonathon: 


![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/3d0c8390-7900-456c-9173-f907e42f87bf)

**Comment by steph-sing** [comment]
error fixed. Push was complete
