### ISSUE TITLE
ARGOS and GlyGen DB Updates: Advanced search for targeted searching

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#362]
From Jeet

This advanced option will allow to search based on categories. E.g A word can be searched in the dataset name/BCO name or in the content of the dataset/bco. It can have a option to select an organism or a file format.(having and / or operators) For eg. search the keyword glycohydrolase in human (9606). The advanced targeted search can be similar to the one implemented in GlyGen Protein Advanced Search - https://www.glygen.org/protein-search/, having multiple fields to narrow down search. We can few fields and or categories to begin with.

**Comment by rykahsay** [comment]
This is a lot of work, and the need for it has to be justified --> meaning, you have to come up with a use case that cannot be achieved by what we have now. One can search for "glycohydrolase" and use the "human" filter to achieve the use case mentioned here.

**Comment by steph-sing** [comment]
@rykahsay I will backlog this and leave it as an item to discuss for ARGOS at a later date with Raja.
