### ISSUE TITLE
ARGOS and GlyGen DB Updates: Home Page updates

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#363]
- [x] On the home page, between the BCO ID and File Name columns, please add a column called 'Description' which pulls from the first sentence of the Usability Domain of the corresponding BCO (provides better up front info about a dataset). 

![Image](https://user-images.githubusercontent.com/70154794/264409831-14f1710e-c8d3-490e-8004-79795f71bf8f.png)

- [ ]  Remove wrapping of filenames and descriptions on Homepage (make columns wider)

![Image](https://user-images.githubusercontent.com/70154794/264410108-196cce58-5889-4d36-b863-72940e4b23a7.png)

**Comment by rykahsay** [comment]
done

**Comment by steph-sing** [comment]
@rykahsay are we able to address this as well? or is it unavoidable?
- [ ]  Remove wrapping of filenames and descriptions on Homepage (make columns wider)

![Image](https://user-images.githubusercontent.com/70154794/264410108-196cce58-5889-4d36-b863-72940e4b23a7.png)

**Comment by rykahsay** [comment]
It is better to leave it like it is now, otherwise it will push the "DETAILS" column outside of the visible area and one would require to slide to see it.

**Comment by steph-sing** [comment]
understood. Thanks
