### ISSUE TITLE
ARGOS and GlyGen DB Updates: Details Page/Card specific view updates

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#364]
- [ ] On the Dataset Detail page, there should be an option to show the full description about the dataset and not just the first sentence (full usability domain)

![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/f0d2e8ce-0b84-4585-9d53-c91ef8253683)

**Comment by rykahsay** [comment]
I am displaying all lines now (making this optional can be done in the future).

**Comment by steph-sing** [comment]
complete
