### ISSUE TITLE
ARGOS and GlyGen DB Updates: Home Page data table column orientation

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#369]
- [ ] Please move the 'BCO TTILE' olumn to be in-between the 'BCO ID' and 'DESCRIPTION' column

![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/48cdf200-15f1-48f2-ba94-d361d82429bd)

**Comment by rykahsay** [comment]
done
<img width="560" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/b11a86f4-1edd-4ce8-bba0-e6b978930158">

**Comment by steph-sing** [comment]
looks great, thanks
