### ISSUE TITLE
ArgosDB Error: Sample view not showing up for 'ARG_' data

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#370]
Under the 'All Records' section of the data, a sample of the data is not showing up, or a python command shows up. These 'ARG_' BCOs correspond to a FASTA file and should show a sample of that. Can you address this error please? 

Data in Question:

![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/4b27d3f3-20fc-4f8b-91f9-9d82f0f3e07c)

Example of Error:

![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/3879545f-cfc1-4a44-8128-6ad71064eee3)

![Image](https://github.com/FDA-ARGOS/data.argosdb/assets/70154794/386aa34c-ca6e-4e11-81e2-eea0302e9ad0)

**Comment by rykahsay** [comment]
Have tried to fix it, please check.

By the way, your BCO IDs are consistent ARGOS_** vs ARG_***

<img width="796" alt="image" src="https://github.com/FDA-ARGOS/data.argosdb/assets/20584876/ff5061ef-59f3-4d77-bfef-df7d568d07af">
