### ISSUE TITLE
FDA Nov. 2023 Monthly Meeting Slides

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS/data.argosdb#388]
- Data Team Updates for the month of Oct
- BETSY progress
- QC paper: publication progress
- Year 3 setup and planning: setup milestones and meetings
- Biosample submission updates: how/when to submit these updates 
- Year 3 kick-off meeting items: current deliverables, transitional activities

**Comment by cwoodside1278** [comment]
- Data Team Updates for the month of Oct
- BETSY progress
- QC paper: publication progress
- Year 3 setup and planning: Closeout documentation setup milestones and meetings
- Biosample submission updates: mock-ups how/when to submit these updates 
- Year 3 kick-off meeting items: current deliverables, transitional activities

**Comment by cwoodside1278** [comment]
The presentation has been updated to the google drive. Also sent out to embleema
