### ISSUE TITLE
Hadley - Run v1.5 Data Dictionary Error Testing

### ISSUE THREAD

**Issue by cwoodside1278** [FDA-ARGOS/data.argosdb#391]
Reach out to Hadley and as him to generate the error testing reports for v1.5 - publication relevant

**Comment by steph-sing** [comment]
@HadleyKing V1.5 data dictionary has been updated and reviewed by both me and Christie. Here is the link: [Final_V1.5_argos_dict](https://docs.google.com/spreadsheets/d/143PKHoEtc7yvfBXmGD6WcVfP89I0dmCHqVrQAlCVJWE/edit?usp=sharing)

Some terms have been updated and all edits have been recorded in the Release Notes. If you get an error per any of these edits, please do not change the data dictionary to be valid per your testing, rather, please update your test scripts to acknowledge the changes in the dictionary. I notice items have continued to be converted back to a previous version based on testing - this just causes us to continuously change it back to the correct item. 

This dictionary version is intended to be cited and used in the QC paper. If you catch any errors outside of the noted changes, please let us know immediately and post them in this ticket so we can have a proper log, and address them. 

We are planning a v1.56 data release tomorrow which includes the v1.5 dd and all dataset schemas updated per 1.5. It would be ideal if you could run these today and at least let us know if any errors have occurred, before publishing. 

once v1.56 is released, you have clearance to create the v.15 GitHub branch per the paper. Please give a recommendation on what should be included in this branch.
