### ISSUE TITLE
Christie - Pick one assembly per genome and run 10 assemblies in batch mode and see if it works. First pick the ones which have only one assembly for that genus.

### ISSUE THREAD

**Issue by cwoodside1278** [FDA-ARGOS/data.argosdb#417]
Testing for HIVE3.

**Comment by penningtonea** [comment]
@steph-sing can assist with testing

**Comment by cwoodside1278** [comment]
Multiple blockers include:
- need to change parameters using HIVE Queen account:
         - Emily and Jonathon will do this

**Comment by cwoodside1278** [comment]
Going to begin single computations today. Xinyang and Emma will be helping with said computations

**Comment by cwoodside1278** [comment]
As of last week, batch mode is still not running.

**Comment by cwoodside1278** [comment]
Batch mode works in HIVE3. Sometimes minor errors, but is relatively running and have had successful batches
