### ISSUE TITLE
Christie - Mapping of variables in HIVE3

### ISSUE THREAD

**Issue by cwoodside1278** [FDA-ARGOS/data.argosdb#420]
We need to provide to Vahan of what is on our data dictionary and what Vahan is calling it when the QC table is spit out of HIVE3. Vahan will then fix his name, so that it is easier for me. 

There are certain variables that are certain QC metrics that WE want, but HIVe3 doe snot currently provide.
- Are they important?
- Should we ask Vahan when/should we get rid of it?

**Comment by penningtonea** [comment]
Initial round of QC variable mapping has been completed and is ready for review. We will present the QC mapping document during our meeting on Wednesday, 1/24 and discuss a plan for the data dictionary and QC metrics in detail.

**Comment by cwoodside1278** [comment]
Variables to be mapped have been provided to Vahan to update

**Comment by cwoodside1278** [comment]
This has been updated and done for v1.6
