### ISSUE TITLE
Try to run the argos pipeline via API scripts

### ISSUE THREAD

**Issue by penningtonea** [FDA-ARGOS/data.argosdb#423]
**SRR upload error seen in workflow**
Most organisms require multiple SRR accessions to accurately analyze the assembly data. The pipeline was run as dictated in the protocol with the stated parameters but threw the following error message pertaining to gathering the SRR data from NCBI and creating a hiveseq object with the data:
![image](https://github.com/FDA-ARGOS/data.argosdb/assets/70979519/81b1beaf-87d1-4525-ba3b-35cfc341c490)

Next step is to try using the api to add multiple SRA files and adjust the existing script to include the parameters necessary. Code snippets for template below.

```
def apiLogin():
   global cookies

   user = input("\nEnter your username on " + hiveVal + " (email address): ")
   password  = getpass.getpass()
   loginParams = {'api': '0', 'cmdr': 'login', 'login': user, 'pswd': password}
   response = requests.get(basename, params=loginParams)
   if response.text != '':
      print(response.text)
      apiLogin()  # Try again
   else:
      cookies = response.cookies

apiLogin()
```

Correct SRR parameters: 

```
lst=[]
strIDs = ','.join(str(v) for v in lst)
SRRParams = {'cmdr': 'propget', 'prop': 'id,_brief', 'mode': 'csv', 'ids': strIDs, 'raw': '1'}
responseSRR = requests.get(basename, SRRParams, cookies=cookies)
decoded_content = responseSRR.content.decode('utf-8')
cr = csv.reader(decoded_content.splitlines(), delimiter=',')
with open('TEMPIDFile.csv', 'w+', newline='') as IDFile:
    my_list = list(cr)
    for row in my_list:
        print(row[3].split()[0], file=IDFile)
```

Alternatively, use the API to read the SRR files into HIVE3. Go to the webpage GUI and run the pipeline with the newly added SRR files by selecting them in the "HIVE reads" field instead of entering the SRA information in "SRR accessions".

**Comment by penningtonea** [comment]
Original code: lib/ngsDataGrabber_V0.6.py

**Comment by cwoodside1278** [comment]
@penningtonea was this fixed?

**Comment by penningtonea** [comment]
Will follow up with @kee007ney regarding this ticket. Script did not work because HIVE3 re-directed from the home page to dna.net

**Comment by cwoodside1278** [comment]
@kee007ney @penningtonea Is this something we still need to fix/work on?

**Comment by penningtonea** [comment]
Additional tickets from the HIVE-Platform repo:
https://github.com/GW-HIVE/Platform/issues/70
https://github.com/GW-HIVE/Platform/issues/71

**Comment by cwoodside1278** [comment]
@penningtonea does this work now?

**Comment by cwoodside1278** [comment]
Not completed and not applicable
