### ISSUE TITLE
Mazumder - organize documentation for the data dictionary and BCO updates

### ISSUE THREAD

**Issue by penningtonea** [FDA-ARGOS/data.argosdb#429]
Data dictionary: Draft definitions and constraints for HIVE3 terms that do not overlap in HIVE2. 

The following BCOs will need to be updated when ARGOS pipeline analysis begins (after pipeline testing is complete) 
BCOs to update:
- property list
- core dataset 
- annotation dataset
- HIVE3 protocol

**Comment by penningtonea** [comment]
Meeting in person on 2/27 to go over data dictionary additions. Need to clarify BCO information with Stephanie. Possibly update data schema for terms.

**Comment by cwoodside1278** [comment]
Waiting for HIVE3 constraints, otherwise it is up to date

**Comment by cwoodside1278** [comment]
What was the consenus on this

**Comment by cwoodside1278** [comment]
@penningtonea I believe this has also been completed, no?

**Comment by cwoodside1278** [comment]
So I am mapping the variables currently (there is another ticket on this). @penningtonea But how do we update the BCOs? Is this something that needs to be updated by @HadleyKing

**Comment by cwoodside1278** [comment]
The data dictionary is up to date and I know Hadley knows how to update the BCOs
