### ISSUE TITLE
Troubleshooting Protocol

### ISSUE THREAD

**Issue by kee007ney** [FDA-ARGOS/data.argosdb#448]
Develop a protocol to test things before they're reported as a bug.

**Comment by kee007ney** [comment]
Example:
- Error is repeatable by another user
- Test reads against other references (check for possibility of corrupt reference files)
- Test reference against other reads (check for possibility of corrupt read files)
- Check that links to data are accessible

(Any other basic things that could cause the system to throw an error.)

Once done present to Vahan/Raja in case they want to add to it. Document will be updated if needed. We will always follow this doc before reporting a bug.

**Comment by cwoodside1278** [comment]
I have begun a protocol [here](https://docs.google.com/document/d/1Mq8ZMdrcjwFgDjo67iBQZFxV6L3wocQCudfp2y6DtQk/edit). I only had one error that came to mind so there is currently only one. As we continue to troubleshoot the newly updated HIVE3 to be passed onto the FDA, I will add more. I will close this out and continue to monitor the protocol as we continue the computations.
