### ISSUE TITLE
HIVE3 Salmonella Computations getting killed

### ISSUE THREAD

**Issue by cwoodside1278** [FDA-ARGOS/data.argosdb#498]
Some Salmonella enterica computations are not running. They complete all of the downloads and steps and then are Killed at 30% in the ARGOS-QC Post Alignment Quality step.

Reilan has also experienced this issue and another with her computations. Some say p_ref_downloader error. She checks the genomes to make sure that there is chromosome information and refseq and they are both there. No reason as to why it will not download the references. 

[table 1](https://docs.google.com/spreadsheets/d/1NexAMgmHNmJDZnPQoBDbMFTJO5NyjB8nwmhQ1fybrYc/edit?usp=sharing)

The first three in this acinebacter pitti failed

[table 2](https://docs.google.com/spreadsheets/d/1O8YblZ05uqYSJwIYoY_TcFHdpPD3aZo_LwecJ_7muNQ/edit?usp=sharing)
second in this spreadsheet acinebacter ursingii failed

**Comment by kee007ney** [comment]
@cwoodside1278 Please share a few example failed computations with me.

**Comment by cwoodside1278** [comment]
I am sharing a folder (obj 48900) that has one fialed and one killed salmonella computation @kee007ney

**Comment by cwoodside1278** [comment]
Also 47569 is another folder with some failed, some killed, and some successful @kee007ney

**Comment by kee007ney** [comment]
Error says `data error detected`. May just be poor quality files. Christie to evaluate the quality of all input files separately.

**Comment by cwoodside1278** [comment]
This is now occuring in some other computations that I am running. The computation steps will all complete up to the last step ARGOS-QC Post Alignment. At the post-alignment step it will get killed at 30%. It is always 300%... so I do not understand what is happening. @kee007ney should we discuss with Vahan?

Also from your previous response, I checked the quality of the files and they looked good. We have no reason to suspect the files are bad. Maybe they are just too large?

**Comment by cwoodside1278** [comment]
My assumption that they were failing was because of the "nucleotide/genome is too long" warning on the Nucleotide page for the organisms. This was an issue I discussed with Vahan and it has been fixed in HIVE3 now with the new update. I have no been able to successfully compute organisms with this warning label, so it cannot be this reason alone.

![Image](https://github.com/user-attachments/assets/31354d80-4692-4e6b-aeec-ec3cf472769b)

I have also checked the downloaded SRR files for some of the failing files and they look perfectly fine to me. I have even been getting this issue if I use FTP or the manual ID input. ARGOSQC always displays 20%, because this is the beginning step. For it to fail at 30% must mean something fail sin the first 1-2 steps of the computations. 

I have tried to download the procmap.csv from the workflow and did not see anything that would help me decipher the error. The error itself specifically says "Killed" and no other information that could be helpful. I even resubmitted the ARGOS-QC post alignment quality computation (not just 'resume') and the exact same thing happened. Not sure why it will not complete when it has already dont heptagon and hexagon perfectly fine.

@kee007ney at this point if sean, you, and I can't figure it out I think we should bring in Vahan.

**Comment by cwoodside1278** [comment]
I talked w/ Sean yesterday and Vahan found the source of the issue. I am just waiting for Vahan to push it to HIVE3.

**Comment by cwoodside1278** [comment]
They have fixed the bug they believe. Sean wants to add one more update, before Jonathon pushes it to our instance. @kee007ney could you let me know when you push it?

**Comment by cwoodside1278** [comment]
It is fixed now. It was because the size of the genomes were too big and it took forever to run. Pushed and updated yesterday dec 18
