### ISSUE TITLE
Possible duplication of ngsQC biosample field

### ISSUE THREAD

**Issue by kerchner** [FDA-ARGOS/data.argosdb#61]
@HadleyKing Is there meant to be a difference between [row 120](https://github.com/FDA-ARGOS/data.argosdb/blob/main/data_dictionary/v0.5/FINAL_v0.5_core_property_list.tsv#L120) and [row 132](https://github.com/FDA-ARGOS/data.argosdb/blob/main/data_dictionary/v0.5/FINAL_v0.5_core_property_list.tsv#L132) in https://github.com/FDA-ARGOS/data.argosdb/blob/main/data_dictionary/v0.5/FINAL_v0.5_core_property_list.tsv?  Or is this a duplication?

**Comment by HadleyKing** [comment]
@kerchner Good catch!
That is a duplicate. 
I will update this for the next release.
