### ISSUE TITLE
SARS-CoV-2 annotation tables (Omicron, Delta mutation, selection pressure etc. annotation tables)

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#8]
This would include mutations mapped to proteins and genome of Ref. Wuhan. For annotation tables - need data model and schema. this schema can remain open if imapped to wuhan genome and proteome. Data dictionary will also need to be updated and master files created.

**Comment by steph-sing** [comment]
complete
