### ISSUE TITLE
use our argosDB dataset APIs and NCBI APIs/eutils for assemblyQC and ngs_id_list

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#94]
The ARGOS DB APIs need to be the entry point for all of the automatically generated and summary tables. To implement this the following prerequisites should be completed
- [x] #95
- [x] #96
- [x] #97
- [x] #98

**Comment by HadleyKing** [comment]
a list of subtasks
- [ ] sometext 
- [ ] more text

**Comment by HadleyKing** [comment]
[beta-test.txt](https://github.com/FDA-ARGOS/data.argosdb/files/10005560/beta-test.txt)
@steph-sing see the attached file.

**Comment by steph-sing** [comment]
@Jgergely11 can you give a status update with this task? are you able to generate the ngs_id_list table via the ngsqc API? If so, please close this task.

**Comment by Jgergely11** [comment]
Yes its done
