### ISSUE TITLE
@HadleyKing Add `argosdb_api_query.py` as the entry point for generation of `assemblyQC_NCBI.tsv`

### ISSUE THREAD

**Issue by HadleyKing** [FDA-ARGOS/data.argosdb#96]

**Comment by HadleyKing** [comment]
Draft is at https://github.com/FDA-ARGOS/data.argosdb/blob/ncbi/lib/argosdb_api_query.py

**Comment by steph-sing** [comment]
goal to finish by 11/4

**Comment by HadleyKing** [comment]
https://github.com/FDA-ARGOS/data.argosdb/commit/3e5724a65db6b5eeb10e369fc353b363cec6fccd
